// OTS SPINS, 1 December 2025 — practice question bank
// Grouped into 16 memorization parts. Each item: { part, ref, q, a }
window.SPINS_PARTS = [
  { n: 1,  title: `Identity & Structure`,               scope: `1.1–1.5, Att 4, Att 1` },
  { n: 2,  title: `Conduct & the Daily Clock`,          scope: `2.1–2.3` },
  { n: 3,  title: `Addressing & Reporting to Staff`,    scope: `2.4.1–2.4.3, 2.4.6–2.4.7, 2.8` },
  { n: 4,  title: `Greeting of the Day & Precedence`,   scope: `2.4.4–2.4.5` },
  { n: 5,  title: `Mandatory Items & Feedback Tools`,   scope: `2.5, 2.9, Att 6` },
  { n: 6,  title: `Customs & Courtesies`,               scope: `2.6` },
  { n: 7,  title: `Academic Buildings`,                 scope: `2.7` },
  { n: 8,  title: `Base Life Policies`,                 scope: `2.10–2.22` },
  { n: 9,  title: `Dress & Appearance`,                 scope: `Chapter 3` },
  { n: 10, title: `Health & Medical`,                   scope: `Chapter 4` },
  { n: 11, title: `Safety, Heat & Weather`,             scope: `Att 5, A2.6` },
  { n: 12, title: `Drill Definitions & Formations`,     scope: `A2.1, A2.2.1–A2.2.5` },
  { n: 13, title: `Entry/Departure, Marching, Guidons`, scope: `A2.2.6–A2.3, A2.5` },
  { n: 14, title: `Road Guards`,                        scope: `A2.4, Att 7` },
  { n: 15, title: `DFAC Arrival`,                       scope: `A3.1–A3.4` },
  { n: 16, title: `DFAC Interior & Departure`,          scope: `A3.5–A3.7` }
];

window.SPINS_QUESTIONS = [

// ─────────── PART 1 — IDENTITY & STRUCTURE ───────────
{ part:1, ref:`1.1`, q:`Recite the OTS Ethos.`, a:`As OTS professionals, we are dedicated to owning the mission. We will purposefully develop as leaders within the Profession of Arms with pride, passion, and unity. We will teach and be taught. We will lead and be led. We will identify and push beyond our perceived limits through courage, resiliency, and hardiness of spirit. We will model the way with a relentless pursuit of excellence… "Always with Honor!"` },
{ part:1, ref:`1.1`, q:`The Ethos names three qualities we develop as leaders with. What are they?`, a:`Pride, passion, and unity.` },
{ part:1, ref:`1.1`, q:`Per the Ethos, we push beyond our perceived limits through what three things?`, a:`Courage, resiliency, and hardiness of spirit.` },
{ part:1, ref:`1.1`, q:`How does the Ethos close?`, a:`We will model the way with a relentless pursuit of excellence… "Always with Honor!"` },
{ part:1, ref:`1.2`, q:`Recite the OTS Vision.`, a:`The premier leader-development institution within the Profession of Arms.` },
{ part:1, ref:`1.3`, q:`Recite the OTS Mission.`, a:`Developing Warrior-Minded Leaders of Character committed to our oath, values, and creed.` },
{ part:1, ref:`1.3`, q:`The Mission says we are committed to what three things?`, a:`Our oath, values, and creed.` },
{ part:1, ref:`1.4`, q:`Recite the OTS Honor Code.`, a:`We will not lie, steal, or cheat, nor tolerate among us anyone who does.` },
{ part:1, ref:`1.5`, q:`When do Officer Trainees enter the Wing?`, a:`Upon successful completion of Module 1.` },
{ part:1, ref:`1.5`, q:`In this manual, what does any reference to "Squadron" or "SQ" refer to?`, a:`OTS permanent party staff.` },
{ part:1, ref:`1.5`, q:`In this manual, what does any reference to "Commander" or "CC" refer to?`, a:`The G-Series permanent party staff commander.` },
{ part:1, ref:`1.5`, q:`How is Officer Trainee Wing leadership within the OT Wing designated?`, a:`Designated or prefaced by "Officer Trainee" or "OT."` },
{ part:1, ref:`1.5`, q:`Which attachment contains the Officer Trainee Wing Structure?`, a:`Attachment 4.` },
{ part:1, ref:`Att 4`, q:`Name the four trainee squadrons.`, a:`Goldhawks (OT SQ 1), Hoyas (OT SQ 2), Mustangs (OT SQ 3), Wolfpack (OT SQ 4).` },
{ part:1, ref:`Att 4`, q:`Which OT squadrons fall under OT Group 1, and which under OT Group 2?`, a:`Group 1: OT Squadrons 1 and 2. Group 2: OT Squadrons 3 and 4.` },
{ part:1, ref:`Att 4`, q:`List the OT Wing A-Staff directorates shown in the Wing structure.`, a:`A1, A23, A4, A5/8, A6, and WSS.` },
{ part:1, ref:`Att 4`, q:`Who does the OT Wing Chief of Staff oversee, and who sits above the OT Wing Commander's deputy?`, a:`The Chief of Staff oversees the Wing A-Staff Directors; the OT Deputy Wing Commander (OT TWG/CD) reports to the OT Wing Commander (OT TWG/CC).` },
{ part:1, ref:`Att 4`, q:`How many flights are shown per OT squadron in the Wing structure?`, a:`Three (e.g., FLT 10, 11, 12 under OT SQ 1).` },
{ part:1, ref:`Title page`, q:`Who is the Commandant that signed the SPINS, and what is their rank?`, a:`Roxanne T. Toy, Colonel, USAF.` },
{ part:1, ref:`Title page`, q:`What publication does the 1 December 2025 SPINS supersede?`, a:`The OTS SPINS dated 18 October 2024.` },
{ part:1, ref:`Title page`, q:`Who is the OPR for the OTS SPINS, and who certified it?`, a:`OPR is OTS Operations; certified by OTS Operations (Lt Col Samuel Backes).` },
{ part:1, ref:`Title page`, q:`What form is used to recommend a change or correction to this publication?`, a:`AF Form 847, Recommendation for Change of Publication, routed through the chain of command.` },
{ part:1, ref:`Att 1`, q:`What does CQ stand for?`, a:`Charge of Quarters.` },
{ part:1, ref:`Att 1`, q:`What does DP stand for?`, a:`Dining Priority.` },
{ part:1, ref:`Att 1`, q:`What does IDMT stand for?`, a:`Independent Duty Medical Technician.` },
{ part:1, ref:`Att 1`, q:`What does LRC stand for?`, a:`Leadership Reaction Course.` },
{ part:1, ref:`Att 1`, q:`What does SMT stand for?`, a:`Scheduled Military Training.` },
{ part:1, ref:`Att 1`, q:`What do PT and PTG stand for?`, a:`Physical Training and Physical Training Gear.` },
{ part:1, ref:`Att 1`, q:`What do PCC, UOD, and MTF stand for?`, a:`Physical Conditioning Center, Uniform of the Day, and Medical Treatment Facility.` },
{ part:1, ref:`Att 1`, q:`What do TRS, DO, and CR stand for?`, a:`Training Squadron, Director of Operations, and Commander's Review.` },
{ part:1, ref:`Att 1`, q:`What is the title of DAFI 36-2903, and of AFI 1-1?`, a:`DAFI 36-2903 is Dress and Personal Appearance of United States Air Force and United States Space Force Personnel. AFI 1-1 is Air Force Standards.` },
{ part:1, ref:`Att 1`, q:`Which publication governs drill and ceremonies, and which governs the physical fitness program?`, a:`DAFPAM 34-1203, Drill and Ceremonies; DAFMAN 36-2905, Air Force Physical Fitness Program.` },

// ─────────── PART 2 — CONDUCT & THE DAILY CLOCK ───────────
{ part:2, ref:`2.1`, q:`How are Officer Trainees addressed?`, a:`As "OT" — e.g., OT Smith or Officer Trainee Smith.` },
{ part:2, ref:`2.1`, q:`Who do references to "Officer Trainee" or "Trainee" in the manual apply to?`, a:`Any trainee assigned to OTS.` },
{ part:2, ref:`2.2.1`, q:`What violations must Officer Trainees report?`, a:`All violations of the Honor Code and UCMJ, to include unprofessional relationships, maltreatment, maltraining, and violations of written or verbal orders.` },
{ part:2, ref:`2.2.1`, q:`Whose misconduct must be reported, and how quickly?`, a:`Any misconduct — by Officer Trainees, faculty/staff, or others — reported to the chain of command immediately.` },
{ part:2, ref:`2.2.1`, q:`Failure to report misconduct may be punishable under which UCMJ article?`, a:`Article 92.` },
{ part:2, ref:`2.2.2`, q:`Which AFI covers professional relationships and conduct, and which paragraph addresses conduct unbecoming?`, a:`AFI 36-2909, Air Force Professional Relationship and Conduct, paragraph 3.1.4.` },
{ part:2, ref:`2.2.2`, q:`Engaging in an unprofessional relationship may violate which UCMJ article, and what is it called?`, a:`Article 133, Conduct Unbecoming an Officer (10 U.S.C. Section 933).` },
{ part:2, ref:`2.2.2`, q:`Where is Article 133 further defined?`, a:`In the Manual for Courts-Martial.` },
{ part:2, ref:`2.3`, q:`Define Scheduled Military Training (SMT).`, a:`The period beginning with lights-on and ending with the last scheduled training event each day — no earlier than dinner Dining Priority on weekdays.` },
{ part:2, ref:`2.3`, q:`What may result from missing SMT hours?`, a:`Commander's Review.` },
{ part:2, ref:`2.3`, q:`After SMT, who approves off-campus activity?`, a:`The owning TRS/DO — OTs must coordinate it for approval.` },
{ part:2, ref:`2.3.1`, q:`What time must OTs be on base, and by what time signed in with CQ accountability?`, a:`On base by 2100L; signed in with Charge of Quarters accountability by 2145L.` },
{ part:2, ref:`2.3.1`, q:`What are the rules on departing the dormitory around accountability?`, a:`Trainees will not depart the dormitory until morning accountability is reported, and will not depart after evening accountability is reported.` },
{ part:2, ref:`2.3.2`, q:`What are quiet hours, and what is each OT's responsibility during them?`, a:`2100–2159L. Each OT is responsible for ensuring their noise level, indoors or outdoors, does not disturb any other OT.` },
{ part:2, ref:`2.3.3`, q:`What are lights out hours?`, a:`2200–0430L.` },
{ part:2, ref:`2.3.3`, q:`Define lights out, and what may be played to initiate it?`, a:`The period when OTs are in their room sleeping. Taps may be played to initiate lights out.` },
{ part:2, ref:`2.3.3`, q:`Who do OTs coordinate with on the playing of Taps?`, a:`Their respective A4.` },
{ part:2, ref:`2.3.4`, q:`When may Officer Trainees return to the dormitories during SMT?`, a:`Only with specific permission from OTS Staff.` },
{ part:2, ref:`2.4`, q:`Who do Officer Trainees consider staff?`, a:`All members assigned to OTS, regardless of rank or status, to include civilians and guests.` },
{ part:2, ref:`2.4`, q:`How do OTs address staff members and other Officer Trainees?`, a:`Using "Sir/Ma'am" or rank and last name.` },
{ part:2, ref:`2.4`, q:`As part of military decorum, what may an OT substitute for "Sir/Ma'am"?`, a:`Rank and last name.` },
{ part:2, ref:`2.4`, q:`What is the rank relationship between OTS staff and OTs for the duration of training, and why?`, a:`OTS staff outrank all OTs — due to positional authority.` },
{ part:2, ref:`2.3.1`, q:`Give both Call to Quarters times in order.`, a:`On base by 2100L, signed in with CQ accountability by 2145L.` },
{ part:2, ref:`2.3.2 / 2.3.3`, q:`State quiet hours and lights out back to back.`, a:`Quiet hours 2100–2159L; lights out 2200–0430L.` },
{ part:2, ref:`2.2.1`, q:`Under what UCMJ article is failure to report punishable, and what is the reporting standard for timing?`, a:`Article 92; reporting is immediate.` },
{ part:2, ref:`2.3`, q:`On weekdays, what is the earliest SMT can end?`, a:`No earlier than dinner Dining Priority.` },
{ part:2, ref:`2.4.1`, q:`In a professional academic environment, how do trainees address each other?`, a:`By OT (Last Name).` },
{ part:2, ref:`2.4.1`, q:`What must accompany all yes/no responses?`, a:`Sir/Ma'am.` },
{ part:2, ref:`2.2`, q:`Name the four categories of misconduct specifically listed as reportable alongside Honor Code and UCMJ violations.`, a:`Unprofessional relationships, maltreatment, maltraining, and violations of written or verbal orders.` },
{ part:2, ref:`2.3.4`, q:`During SMT, what is the default rule about the dormitories?`, a:`OTs will not return to the dormitories during SMT.` },

// ─────────── PART 3 — ADDRESSING & REPORTING TO STAFF ───────────
{ part:3, ref:`2.4.3`, q:`List all seven basic responses in order.`, a:`1) "Yes, Sir/Ma'am." 2) "No, Sir/Ma'am." 3) "Sir/Ma'am, I do not know." 4) "Sir/Ma'am, I do not understand." 5) "Sir/Ma'am, may I ask a question?" 6) "Sir/Ma'am, may I make a statement?" 7) "Sir/Ma'am, the answer is."` },
{ part:3, ref:`2.4.3`, q:`What is the 3rd basic response?`, a:`"Sir/Ma'am, I do not know."` },
{ part:3, ref:`2.4.3`, q:`What is the 4th basic response?`, a:`"Sir/Ma'am, I do not understand."` },
{ part:3, ref:`2.4.3`, q:`What is the 5th basic response?`, a:`"Sir/Ma'am, may I ask a question?"` },
{ part:3, ref:`2.4.3`, q:`What is the 6th basic response?`, a:`"Sir/Ma'am, may I make a statement?"` },
{ part:3, ref:`2.4.3`, q:`What is the 7th basic response?`, a:`"Sir/Ma'am, the answer is."` },
{ part:3, ref:`2.4.3`, q:`For situations not specified by the seven basic responses, what does an OT do?`, a:`Begin or end every sentence with Sir/Ma'am.` },
{ part:3, ref:`2.4.2`, q:`List the four steps, in order, when an OT is addressed by a staff member.`, a:`1) Assume the position of attention prior to speaking or when addressed. 2) Respond with one of the 7 basic responses. 3) Assume the rest position for the duration of the conversation or when answering. 4) When the conversation is over, assume the position of attention, give the greeting of the day, and salute as appropriate.` },
{ part:3, ref:`2.4.2.1`, q:`What position does an OT assume prior to speaking or when addressed by staff?`, a:`The position of attention.` },
{ part:3, ref:`2.4.2.3`, q:`What position does the OT hold for the duration of the conversation?`, a:`The rest position.` },
{ part:3, ref:`2.4.2.4`, q:`What are the three actions when the conversation ends?`, a:`Assume the position of attention, give the greeting of the day, and salute as appropriate.` },
{ part:3, ref:`2.4.1`, q:`How do trainees address staff in the academic environment?`, a:`By Rank/Last Name or with Sir/Ma'am, as appropriate.` },
{ part:3, ref:`2.4.6`, q:`How should delivery of the greeting of the day sound?`, a:`Clear and confident, from an appropriate distance.` },
{ part:3, ref:`2.4.7`, q:`What must OTs announce when entering and departing staff office areas (cube city)?`, a:`Clearly state "OT(s) in the area" and "OT(s) departing the area."` },
{ part:3, ref:`2.8.1`, q:`Walk through reporting procedures when directed to report.`, a:`Center on the threshold of the door or cubicle entrance and knock once loud enough to be heard. Once acknowledged, enter using the most direct route, center two paces in front of the desk or staff member (if possible), salute if the staff member is a commissioned officer, and give the appropriate reporting statement.` },
{ part:3, ref:`2.8.1`, q:`How many times does an OT knock when reporting, and how loudly?`, a:`Once, loud enough to be heard.` },
{ part:3, ref:`2.8.1`, q:`Where does an OT center themselves before knocking?`, a:`On the threshold of the door or cubicle entrance.` },
{ part:3, ref:`2.8.1`, q:`How far in front of the desk or staff member does the OT center themselves?`, a:`Two paces away, if possible.` },
{ part:3, ref:`2.8.1`, q:`When reporting in, when does the OT salute?`, a:`If the staff member is a commissioned officer.` },
{ part:3, ref:`2.8.2`, q:`Give the reporting statement for multiple OTs reporting in to an office/cubicle.`, a:`One OT salutes as appropriate and states, "Sir/Ma'am, (Officer Trainee) (Last Name) plus (number of Officer Trainees) reports as ordered."` },
{ part:3, ref:`2.8.2`, q:`When a group departs an office, who salutes and gives the greeting of the day?`, a:`The Officer Trainee who reported-in, for the entire group.` },
{ part:3, ref:`2.8.2`, q:`What route do OTs take out of the office?`, a:`The most direct route.` },
{ part:3, ref:`2.8.2`, q:`If told to take a seat while reporting in, what do OTs do?`, a:`Take their seat.` },
{ part:3, ref:`2.4`, q:`Why do OTS staff outrank all OTs for the duration of training?`, a:`Due to positional authority.` },
{ part:3, ref:`2.4.2.2`, q:`Step two of being addressed by staff is what?`, a:`Respond with one of the seven basic responses.` },
{ part:3, ref:`2.4.7`, q:`What is the informal name for the staff office areas referenced in the SPINS?`, a:`Cube city.` },
{ part:3, ref:`2.6.1.1`, q:`When reporting to enlisted staff members, do you salute?`, a:`No — except during Open Ranks Inspections.` },
{ part:3, ref:`2.6.1.1`, q:`Indoors, what are the only two situations in which an OT salutes?`, a:`Formally reporting in to a commissioned staff member's office/cubicle, or upon receiving an award at an awards ceremony.` },
{ part:3, ref:`2.4.3`, q:`What are the first two of the seven basic responses?`, a:`"Yes, Sir/Ma'am." and "No, Sir/Ma'am."` },
{ part:3, ref:`2.4.2`, q:`Unless otherwise directed, how must an OT respond when any staff member addresses them?`, a:`With one of the seven basic responses.` },
{ part:3, ref:`2.8.1`, q:`After being acknowledged at the door, what route does the OT take to the staff member?`, a:`The most direct route.` },
{ part:3, ref:`A3.3.1`, q:`When a Flight Leader is reporting in to the Mess Checker, what happens if commissioned staff pass by?`, a:`Neither the Mess Checker nor the Flight Leader will interrupt reporting procedures to greet and salute commissioned staff.` },

// ─────────── PART 4 — GREETING OF THE DAY & PRECEDENCE ───────────
{ part:4, ref:`2.4.4`, q:`State all three greeting-of-the-day time windows.`, a:`"Good morning, Sir/Ma'am" from 0000 until 1159L; "Good afternoon, Sir/Ma'am" from 1200 until 1659L; "Good evening, Sir/Ma'am" from 1700 until 2359L.` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 1159L?`, a:`"Good morning, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 1200L?`, a:`"Good afternoon, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 1659L?`, a:`"Good afternoon, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 1700L?`, a:`"Good evening, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 2359L, and at 0001L?`, a:`2359L is "Good evening, Sir/Ma'am"; 0001L is "Good morning, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What are the two exceptions to giving the proper greeting of the day when passing OTS staff?`, a:`When the staff member is engaged in a conversation, or when in the latrine.` },
{ part:4, ref:`2.4.4.1`, q:`Indoors, in groups of four or fewer, who gives the greeting of the day?`, a:`All OTs give the appropriate greeting of the day.` },
{ part:4, ref:`2.4.4.1`, q:`Outdoors, in groups of four or fewer, what do OTs do?`, a:`All OTs render salutes as applicable and give the greeting of the day.` },
{ part:4, ref:`2.4.4.2`, q:`Indoors, in groups of five or more, who gives the greeting of the day?`, a:`The first OT in line gives the appropriate greeting of the day for the entire group.` },
{ part:4, ref:`2.4.4.2`, q:`Outdoors and not in formation, in groups of five or more, what do OTs do?`, a:`All individuals render salutes as applicable and give the greeting of the day.` },
{ part:4, ref:`2.4.5`, q:`State the general rule for greeting order of precedence.`, a:`Render the greeting of the day to the highest-ranking individual first when approaching a group.` },
{ part:4, ref:`2.4.5`, q:`Greet a male Major walking with a female Captain.`, a:`"Good morning, Sir, Good morning, Ma'am."` },
{ part:4, ref:`2.4.5.1`, q:`If individuals are of the same rank, who is greeted first?`, a:`The female(s).` },
{ part:4, ref:`2.4.5.1`, q:`Greet a female Captain walking with a male Captain.`, a:`"Good morning, Ma'am, Good morning, Sir."` },
{ part:4, ref:`2.4.5.2`, q:`If all individuals are of the same sex, how are they greeted?`, a:`As a group with "Ladies" or "Gentlemen."` },
{ part:4, ref:`2.4.5.2`, q:`Greet a male Major and a male Captain.`, a:`"Good morning, Gentlemen."` },
{ part:4, ref:`2.4.5.3`, q:`If rank is indeterminable, who is greeted first?`, a:`The female(s).` },
{ part:4, ref:`2.4.5.3`, q:`Greet a group of four males and two females in the PT uniform.`, a:`"Good morning, Ladies. Good morning, Gentlemen."` },
{ part:4, ref:`2.4.5.4`, q:`If an OT knows the staff member, how may they be greeted?`, a:`By name in rank order — e.g., "Good morning, Major Smith; Good morning, Master Sergeant Scarib."` },
{ part:4, ref:`2.4.5.4`, q:`Give two examples of staff an OT would know well enough to greet by name.`, a:`Their Flight Commander or assigned MTI.` },
{ part:4, ref:`2.4.6`, q:`Two qualities the delivery of the greeting must have, plus one condition.`, a:`Clear and confident, from an appropriate distance.` },
{ part:4, ref:`2.4.4`, q:`What change did the 1 December 2025 SPINS make regarding the greeting of the day and the latrine?`, a:`Greeting of the day is not authorized in the latrine.` },
{ part:4, ref:`2.6.1.2`, q:`Outdoors, passing an officer who is engaged in conversation — what does the OT do?`, a:`Render a salute but not interrupt with the greeting of the day.` },
{ part:4, ref:`2.6.1.3`, q:`Is a greeting required when either staff or OTs are in PTG?`, a:`Yes — saluting is not required in PTG, but OTs will render the proper greeting of the day.` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 0500L?`, a:`"Good morning, Sir/Ma'am."` },
{ part:4, ref:`2.4.4`, q:`What is the greeting at 2100L?`, a:`"Good evening, Sir/Ma'am."` },
{ part:4, ref:`2.4.5`, q:`Greet a group where a Colonel walks with a Lieutenant Colonel, both male.`, a:`"Good morning, Gentlemen" — same sex, so greet as a group.` },
{ part:4, ref:`2.4.4.1 / 2.4.4.2`, q:`What is the group-size cutoff that changes who greets indoors?`, a:`Four or fewer: all OTs greet. Five or more: the first OT in line greets for the group.` },
{ part:4, ref:`2.7.4.3`, q:`When recognized to ask or answer a question in an auditorium, where does the greeting of the day fall in the sequence?`, a:`Stand at attention, provide the greeting of the day, state OT and Last Name, then ask or answer.` },
{ part:4, ref:`A3.5.1`, q:`Are OTs required to greet in the DFAC?`, a:`No, but they must still adhere to customs and courtesies.` },
{ part:4, ref:`2.4.4`, q:`Recite the full afternoon window with its exact end time.`, a:`"Good afternoon, Sir/Ma'am" from 1200 until 1659L.` },

// ─────────── PART 5 — MANDATORY ITEMS & FEEDBACK TOOLS ───────────
{ part:5, ref:`2.5.2.1`, q:`List all seven mandatory items carried on the trainee's person at all times.`, a:`1) Identification Card, 2) Hydration System, 3) Writing Implement/Material, 4) Two properly filled out copies of the AETC Form 341, 5) Reflective Belt, 6) OTS SPINS, 7) Two copies of your orders.` },
{ part:5, ref:`2.5.2.1.1`, q:`What counts as an acceptable identification card?`, a:`Government issued photo ID — e.g., Common Access Card, Driver's License, Passport.` },
{ part:5, ref:`2.5.2.1.3`, q:`What writing implement and material are required?`, a:`Pencil or blue or black ink pen, and paper to take notes.` },
{ part:5, ref:`2.5.2.1.3`, q:`What is the exception to carrying writing implement/material?`, a:`Not required for PT sessions.` },
{ part:5, ref:`2.5.2.1.4`, q:`How many copies of the AETC Form 341 are carried, and IAW what?`, a:`Two properly filled out copies, IAW Attachment 6.` },
{ part:5, ref:`2.5.2.1.7`, q:`How many copies of your orders must be carried?`, a:`Two (2).` },
{ part:5, ref:`2.5`, q:`What is the standardization standard for Officer Trainees?`, a:`Officer Trainees will always present a standardized and professional image.` },
{ part:5, ref:`2.5.1`, q:`In academic areas and outdoor events, what is the standard for equipment and gear?`, a:`Standardize all equipment/gear to the maximum extent possible to present a neat, orderly, and organized appearance.` },
{ part:5, ref:`2.5.2`, q:`What is the standard for uniform wear?`, a:`Standardize uniform wear to the maximum extent, while exercising good judgement and appropriate decision making.` },
{ part:5, ref:`2.9.1`, q:`What is the AETC Form 341 called, and what is it used for?`, a:`Excellence/Discrepancy Report — used to address positive and/or negative Officer Trainee performance.` },
{ part:5, ref:`2.9.1`, q:`Which blocks of the AETC Form 341 must be legibly filled in, and in what ink?`, a:`Name, Grade (OT), Organization, and Class/Flight — in blue or black ink.` },
{ part:5, ref:`Att 6`, q:`How is the name written on the AETC Form 341?`, a:`In all caps: LAST NAME, FIRST NAME and MIDDLE INITIAL — no punctuation or dashes in this block.` },
{ part:5, ref:`Att 6`, q:`What grade goes on the 341, and does direct commissioning change it?`, a:`Everyone's grade will be OT, even if direct commissioned.` },
{ part:5, ref:`Att 6`, q:`What goes in the Organization block of the 341?`, a:`The assigned trainee Squadron — e.g., Goldhawks, Hoyas, Mustangs, Wolfpack.` },
{ part:5, ref:`Att 6`, q:`What determines the Class/Flight block on the 341?`, a:`It will be IAW registrar.` },
{ part:5, ref:`Att 6`, q:`Name the remaining blocks on the AETC Form 341 below the discrepancy narrative.`, a:`Time, Date, Place, Printed Name of Reporting Individual, and Signature of Reporting Individual.` },
{ part:5, ref:`2.9.2`, q:`What is Motivational Training (MT), and what is its purpose?`, a:`Physical exercises designed to motivate trainees to follow OTS standards and expectations; used to correct lapses in procedures and motivate trainees to work as a team.` },
{ part:5, ref:`2.9.2`, q:`Who may administer Motivational Training?`, a:`Qualified staff.` },
{ part:5, ref:`2.9.3`, q:`What is Form 2, and when is it used?`, a:`OTS Leadership Development Report — used at the discretion of the staff to document performance during leadership activities.` },
{ part:5, ref:`2.9.4`, q:`What is Form 6 used for?`, a:`Form 6, Briefing Evaluation Sheet — used to evaluate briefings.` },
{ part:5, ref:`2.9.5`, q:`What is Form 9 used for?`, a:`Form 9, Paper Evaluation Form — used to evaluate writing assignments.` },
{ part:5, ref:`2.9.6`, q:`What does RIC stand for, and what are RICs and memorandums used for?`, a:`Record of Individual Counseling — a means of documenting Officer Trainee performance expectations.` },
{ part:5, ref:`2.9.6`, q:`What is the effect of excessive negative documents?`, a:`They affect an Officer Trainee's ability to successfully complete OTS.` },
{ part:5, ref:`2.9.6`, q:`What must an OT do upon receiving a memorandum or RIC?`, a:`Acknowledge receipt of all memorandums and RICs.` },
{ part:5, ref:`2.9.6.1`, q:`How long does an OT have to respond to feedback, to whom, and IAW what?`, a:`Up to three duty days from the event, submitted to their Flight Commander, written IAW AFH 33-337, Tongue and Quill.` },
{ part:5, ref:`2.9.6.1`, q:`What is the title of AFH 33-337?`, a:`The Tongue and Quill.` },
{ part:5, ref:`2.9.1`, q:`What is the minimum number of AETC Form 341 copies an OT carries at all times?`, a:`A minimum of two copies.` },
{ part:5, ref:`2.5.2.1.5`, q:`Where are approved deviations for the reflective belt found?`, a:`Chapter 3.` },
{ part:5, ref:`2.5.2.1.2`, q:`Which paragraph covers further hydration system requirements?`, a:`Paragraph 3.4.` },
{ part:5, ref:`2.9`, q:`Name all five numbered feedback and evaluation tools in paragraph 2.9.`, a:`AETC Form 341 (Excellence/Discrepancy Report), Motivational Training, Form 2 (Leadership Development Report), Form 6 (Briefing Evaluation Sheet), and Form 9 (Paper Evaluation Form) — plus memorandums and RICs.` },

// ─────────── PART 6 — CUSTOMS & COURTESIES ───────────
{ part:6, ref:`2.6.1`, q:`By what training day is saluting taught as a formal lesson, and IAW what publication?`, a:`By training day three, IAW AFI 1-1, Air Force Standards.` },
{ part:6, ref:`2.6.1.1`, q:`When do OTs salute indoors?`, a:`Only when formally reporting in to a commissioned staff member's office/cubicle, or upon receiving an award at an awards ceremony.` },
{ part:6, ref:`2.6.1.1`, q:`Do OTs salute when reporting to enlisted staff members?`, a:`No — except during Open Ranks Inspections.` },
{ part:6, ref:`2.6.1.2`, q:`Outdoors, what does an OT do when passing an officer engaged in conversation?`, a:`Render a salute but not interrupt with the greeting of the day.` },
{ part:6, ref:`2.6.1.2`, q:`If the officer does not return the salute, what does the OT do?`, a:`Continue and drop the salute once abreast the officer(s).` },
{ part:6, ref:`2.6.1.3`, q:`Is saluting required in PTG, and what is still required?`, a:`Saluting is not required when either staff or OTs are in PTG; the proper greeting of the day is still rendered.` },
{ part:6, ref:`2.6.2`, q:`List all no-salute areas.`, a:`LRC, assault/confidence courses, Blue Thunder, Vigilant Warrior, running track, the covered breezeway between Gilbert Hall and Gilbert Hall Annex, Ritchey Center, Sim City, and Dojo — plus any field leadership event.` },
{ part:6, ref:`2.6.2`, q:`Which location was added to the no-salute area list in the 1 December 2025 SPINS?`, a:`Sim City.` },
{ part:6, ref:`2.6.2`, q:`Is saluting required at field leadership events?`, a:`No — saluting is not required at any field leadership event.` },
{ part:6, ref:`2.6.2`, q:`Which two named field events appear on the no-salute list?`, a:`Blue Thunder and Vigilant Warrior.` },
{ part:6, ref:`2.6.3.1`, q:`When are flags on stationary flag staffs saluted?`, a:`Only during reveille, retreat, or special ceremonies.` },
{ part:6, ref:`2.6.3.1`, q:`Walk through reveille and retreat procedures when outside and in uniform.`, a:`Stop what you are doing, face the direction of the flag (if visible) or the music. Stand at parade rest during the sounding of retreat or reveille, then come to attention and salute during the playing of the National Anthem or "To the Colors."` },
{ part:6, ref:`2.6.3.1`, q:`What position do you hold during the sounding of retreat or reveille?`, a:`Parade rest.` },
{ part:6, ref:`2.6.3.1`, q:`During what music do you come to attention and salute?`, a:`During the playing of the National Anthem or "To the Colors."` },
{ part:6, ref:`2.6.3.1`, q:`What was added to paragraph 2.6.3.1 in the 1 December 2025 change?`, a:`"To The Colors" was added when rendering customs and courtesies.` },
{ part:6, ref:`2.6.3.1`, q:`What do you do if driving a vehicle during reveille or retreat?`, a:`Stop if consistent with safety and mission requirements; Airmen and their passengers should sit quietly until the music ends.` },
{ part:6, ref:`2.6.3.2`, q:`Indoors during a ceremony, in uniform, when the National Anthem plays — what do you do?`, a:`Assume the position of attention, face the flag, but do not salute.` },
{ part:6, ref:`2.6.3.2`, q:`In civilian clothes, indoors or outdoors, when the National Anthem plays?`, a:`Assume the position of attention and place the right hand over the heart; if wearing a hat, it should be removed.` },
{ part:6, ref:`2.6.3.2`, q:`Outdoors and uniformed during the National Anthem — what is the procedure?`, a:`Face the flag or the music if the flag is not visible, render a salute upon hearing the first note, and hold the salute until the conclusion.` },
{ part:6, ref:`2.6.3.2`, q:`Is saluting outdoors in civilian clothes permitted?`, a:`Permitted, but not required.` },
{ part:6, ref:`2.6.3.3`, q:`What are the three exceptions where normal customs and courtesies are not required for Reveille, Retreat, or the National Anthem?`, a:`When participating in PT, Leadership Exercises, or Warrior Events — OTs and staff should continue with these activities.` },
{ part:6, ref:`2.6.3.1`, q:`If the flag is not visible during reveille or retreat, what do you face?`, a:`The music.` },
{ part:6, ref:`2.6.1.1`, q:`Is a salute rendered when receiving an award indoors?`, a:`Yes — that is one of the two authorized indoor salutes.` },
{ part:6, ref:`2.6.2`, q:`Which breezeway is a no-salute area?`, a:`The covered breezeway between Gilbert Hall and Gilbert Hall Annex.` },
{ part:6, ref:`2.6.2`, q:`Is the Ritchey Center a salute or no-salute area?`, a:`No-salute area — though OTs may not use or traverse it unescorted.` },
{ part:6, ref:`2.6.2`, q:`Is the running track a no-salute area?`, a:`Yes.` },
{ part:6, ref:`2.6.1`, q:`Which publication is the authority for saluting instruction at OTS?`, a:`AFI 1-1, Air Force Standards.` },
{ part:6, ref:`2.6.3.1`, q:`Which precedes the lowering of the flag — retreat or the National Anthem?`, a:`The sounding of retreat precedes the lowering of the flag.` },
{ part:6, ref:`2.6.3.2`, q:`When exactly does the salute begin and end during the outdoor National Anthem?`, a:`Begins upon hearing the first note, held until the conclusion.` },
{ part:6, ref:`A2.4.1.4`, q:`If a staff vehicle approaches while the flight is crossing an intersection, does the road guard salute?`, a:`No — due to safety. The person in charge marches the flight across, halts, calls in the road guards, then renders courtesies.` },
{ part:6, ref:`A2.1.1`, q:`In SMU formations, who salutes and extends military courtesies?`, a:`All members of the SMU.` },
{ part:6, ref:`A2.1.2`, q:`In flight formations, who renders the military courtesies?`, a:`The Flight Leader, for the formation.` },

// ─────────── PART 7 — ACADEMIC BUILDINGS ───────────
{ part:7, ref:`2.7.1`, q:`When is talking permitted outside of academic building classrooms?`, a:`Only when making on-the-spot corrections to other Officer Trainees or giving the greeting of the day.` },
{ part:7, ref:`2.7.1`, q:`When may OTs talk quietly inside the flight room?`, a:`Until the Class/Flight Leader instructs them to prepare for instruction.` },
{ part:7, ref:`2.7.2`, q:`How do OTs move through hallways?`, a:`March in a single file, at the position of attention, on the right side of the hallway — to include the Annex breezeway.` },
{ part:7, ref:`2.7.2`, q:`What may OTs not do on carpeted areas?`, a:`Perform facing movements.` },
{ part:7, ref:`2.7.3`, q:`What do OTs do in the PAC and IDMT waiting area?`, a:`Remain seated and read the OTS SPINS until called for by a staff member.` },
{ part:7, ref:`2.7.3`, q:`What does PAC stand for?`, a:`Personnel Action Center.` },
{ part:7, ref:`2.7.4`, q:`How do OTs fill auditorium seats?`, a:`Enter and fill the seats starting in the front, according to the seating arrangement assigned by Officer Trainee leadership.` },
{ part:7, ref:`2.7.4`, q:`What do OTs do while waiting for the lecturer's instruction to take seats?`, a:`Remain standing at ease, quiet, and studying OTS SPINS; then sit at ease and remain attentive.` },
{ part:7, ref:`2.7.4.1`, q:`Walk through the auditorium opening procedure.`, a:`The class leader comes to the position of attention, centered in front of the stage, states "STANDBY" to allow for putting away all materials including the OTS SPINS, then calls the room to attention once they see the instructor approaching.` },
{ part:7, ref:`2.7.4.1`, q:`What command allows for the putting away of all materials in the auditorium?`, a:`"STANDBY."` },
{ part:7, ref:`2.7.4.2`, q:`Walk through the auditorium closing procedure.`, a:`The class leader comes to attention, marches directly to the center in front of the stage, and commands "Class, prepare for dismissal." OTs set aside class materials and stand at Parade Rest; the class leader then calls the room to attention. When the instructor departs they command "CARRY ON" and the class responds "ALWAYS WITH HONOR."` },
{ part:7, ref:`2.7.4.2`, q:`What is the auditorium dismissal command given by the class leader?`, a:`"Class, prepare for dismissal."` },
{ part:7, ref:`2.7.4.2`, q:`What position do OTs assume after setting aside class materials during auditorium closing?`, a:`Parade Rest.` },
{ part:7, ref:`2.7.4.2`, q:`If the instructor does not give "CARRY ON," what happens?`, a:`The class leader commands "CARRY ON" once the instructor/lecturer has left the auditorium, and the class responds with "ALWAYS WITH HONOR."` },
{ part:7, ref:`2.7.4.2`, q:`After "ALWAYS WITH HONOR," what do OTs do?`, a:`Follow staff direction; if there is no direction, prepare for the next lesson by transiting back to their flight room or the designated event location.` },
{ part:7, ref:`2.7.4.3`, q:`Give the full sequence for asking or answering a question during an auditorium lecture.`, a:`Remain seated and raise your hand. When recognized: stand at attention, provide the greeting of the day, state OT and Last Name, ask or answer the question, and stand at ease until the dialogue is complete or you are invited to sit.` },
{ part:7, ref:`2.7.4.4`, q:`Where do OTs sit if they arrive late to an auditorium lecture?`, a:`In the back of the auditorium, without disrupting the lecture.` },
{ part:7, ref:`2.7.4.5`, q:`What are the only reasons an OT may leave the auditorium during a lecture?`, a:`Unforeseen health issues and staff-directed/approved appointments.` },
{ part:7, ref:`2.7.4.5`, q:`If an OT must leave a lecture, how do they return?`, a:`Reenter discreetly and sit in the back of the auditorium.` },
{ part:7, ref:`2.7.4.5`, q:`An OT is directed to leave for disrupting the lecture. What must they do?`, a:`Immediately notify their Flight Commander.` },
{ part:7, ref:`2.7.5.1`, q:`What four items go on the flight room Heads-Up Display?`, a:`Lesson title, instructor's rank and name, scheduled time, and the cognitive samples of behavior for that lecture.` },
{ part:7, ref:`2.7.5.1`, q:`Where on the white board is the Heads-Up Display written, and who ensures it?`, a:`On the left side as viewed from the back of the room, neatly and legibly — the Flight Leader ensures it before each flight room lecture.` },
{ part:7, ref:`2.7.5.2`, q:`Where does the Flight Leader sit in the flight room?`, a:`In the position closest to the white board, to easily view the door.` },
{ part:7, ref:`2.7.5.4`, q:`Walk through flight room opening procedures.`, a:`Prior to the instructor entering, all trainees are at parade rest, standing behind their chairs, facing the center of the room. As the instructor crosses the doorway threshold, the Flight Leader assumes the position of attention and calls the room to attention. The instructor commands "TAKE YOUR SEATS" or "SEATS."` },
{ part:7, ref:`2.7.5.4`, q:`What two commands may the instructor give to seat the flight?`, a:`"TAKE YOUR SEATS" or "SEATS."` },
{ part:7, ref:`2.7.5.5`, q:`Walk through flight room closing procedures.`, a:`The Flight Leader stands, pushes in their chair, assumes attention behind it, and commands "Flight, prepare for dismissal." Each member stands, pushes in their chair, standardizes materials, and assumes Parade Rest behind their chair. The Flight Leader confirms standardization, assumes attention, and calls the room to attention. As the instructor breaks the threshold they command "CARRY ON" and the flight responds "ALWAYS WITH HONOR."` },
{ part:7, ref:`2.7.5.5`, q:`What is the flight room dismissal command?`, a:`"Flight, prepare for dismissal."` },
{ part:7, ref:`2.7.5.5`, q:`What must the last OT departing the flight room do?`, a:`Ensure all audiovisual equipment (except the computer) and lights are off.` },
{ part:7, ref:`2.7.5.3`, q:`What is the requirement for training materials in the flight room?`, a:`All required training materials will be in place and ready for use; display provided lesson slides at the request of the Flight Commander.` },
{ part:7, ref:`2.7.6.1`, q:`If a lecture is actively in session and a visitor enters, do OTs call the room to attention?`, a:`No — regardless of rank, and this includes the instructor.` },
{ part:7, ref:`2.7.6.2`, q:`When a lecture is not in session, when is the room called to attention?`, a:`When a commissioned staff member enters or exits, provided there is not already a commissioned staff member in the room of equal or higher rank.` },
{ part:7, ref:`2.7.6.2`, q:`Who calls the room to attention when an officer breaks the threshold, and what command may be used to prepare?`, a:`The first Officer Trainee to see the officer; OTs may prepare using the "STANDBY" command.` },
{ part:7, ref:`2.7.6.3`, q:`For field leadership events, IAW what do OTs form up for pre- and post-event briefs?`, a:`IAW Attachment 7.` },
{ part:7, ref:`2.7.7`, q:`What is required to use OTS conference rooms and non-classroom spaces?`, a:`Pre-coordination with the owning agency.` },
{ part:7, ref:`2.7.6.2`, q:`Does "not in session" include lesson breaks?`, a:`Yes — including during lesson breaks.` },

// ─────────── PART 8 — BASE LIFE POLICIES ───────────
{ part:8, ref:`2.10`, q:`Define a security violation.`, a:`When Officer Trainees intentionally or unintentionally permit the release or loss of controlled information, materials, or funds.` },
{ part:8, ref:`2.10`, q:`Give four examples of security violations.`, a:`Leaving dorm room security drawers unlocked when rooms are unoccupied, leaving electronic devices unsecured, leaving PII or ID cards unattended, and release of OTS Graded Measures and study materials.` },
{ part:8, ref:`2.10`, q:`When are laptops and items in backpacks considered secured?`, a:`When left in an OT's dorm room or flight room, provided the system is password or biometrically protected.` },
{ part:8, ref:`2.11.1`, q:`How much time may OTs be allotted for worship services, and where?`, a:`Up to 1 hour, on Maxwell AFB or virtual services.` },
{ part:8, ref:`2.11.2`, q:`Where is the Reflection and Accommodation Center located?`, a:`Second floor of building 1487, Room C211.` },
{ part:8, ref:`2.11.2`, q:`Who may an OT discuss religious accommodation with?`, a:`The Holm Center/OTS Chaplain or their chain of command.` },
{ part:8, ref:`2.12`, q:`Which AFI governs OTs accessing government information systems, and which governs social media use?`, a:`AFI 17-130, Cybersecurity Program Management; social media use is subject to AFI 1-1.` },
{ part:8, ref:`2.12`, q:`Violations of network and social media provisions fall under which UCMJ article, and what may result?`, a:`Article 92 — and violations may be grounds for Commander's Review.` },
{ part:8, ref:`2.12.1`, q:`What training must be completed before using any computer connected to a .mil network?`, a:`DoD Information Assurance Cyber Awareness Challenge training.` },
{ part:8, ref:`2.12.1`, q:`Does the Cyber Awareness Challenge requirement apply to the OTS-provided Wi-Fi?`, a:`No.` },
{ part:8, ref:`2.12.1`, q:`What is the OTS Wi-Fi network name?`, a:`AWAKEN.` },
{ part:8, ref:`2.12.2`, q:`When are electronic devices considered secured, and where may they be left?`, a:`When password protected; they may be left in flight or dormitory rooms as training needs dictate.` },
{ part:8, ref:`2.12.2`, q:`Where must external storage and communication devices be secured when not in use?`, a:`In security drawers.` },
{ part:8, ref:`2.13`, q:`What approval is required for food delivery to the OTS campus?`, a:`TRS SQ/CC approval.` },
{ part:8, ref:`2.14`, q:`State the alcohol policy.`, a:`Officer Trainees are not authorized possession or consumption of alcohol.` },
{ part:8, ref:`2.15`, q:`State the tobacco and nicotine policy.`, a:`Officer Trainees are not authorized possession or consumption of tobacco or nicotine products.` },
{ part:8, ref:`2.16.1`, q:`What locations make up the OTS Campus?`, a:`The DFAC, academic areas, Physical Conditioning Center, basketball court, quarter-mile track, drill pad, pull-up bars, and dormitories.` },
{ part:8, ref:`2.16.2`, q:`List the off-campus locations named in the SPINS.`, a:`Paperclip running track, volleyball courts, athletic fields, Fairchild Library (academic study purposes only), and the AU/OTS Shoppette (Express & Military Clothing Sales Store).` },
{ part:8, ref:`2.16.2`, q:`What is Fairchild Library authorized for?`, a:`Academic study purposes only.` },
{ part:8, ref:`2.16.2`, q:`Who approves other off-campus locations, and who may approve single-event usage?`, a:`TRS SQ/CC approval; Module ADO may approve single event usage on a case-by-case basis. Route requests through the OT chain of command.` },
{ part:8, ref:`2.16.3`, q:`Which building is unauthorized, and what does the restriction include?`, a:`Ritchey Center, building 1425 — including its playground, courtyard, and sidewalks. OTs will not use or traverse it unescorted.` },
{ part:8, ref:`2.16.3`, q:`What else is off limits to Officer Trainees?`, a:`Staff break rooms.` },
{ part:8, ref:`2.16.3`, q:`Approval for all other locations, including on-base commercial food vendors, is delegated no lower than whom?`, a:`The TRS SQ/DO.` },
{ part:8, ref:`2.17`, q:`What is required to use or access a POV?`, a:`Prior OTS staff coordination and authorization.` },
{ part:8, ref:`2.17.1`, q:`By when must OTs retrieve all items needed for OTS from their POV?`, a:`By the end of training day two.` },
{ part:8, ref:`2.17.1`, q:`After training day two, what must an OT do to gain POV access?`, a:`Submit an official memorandum to the TRS SQ/ADO.` },
{ part:8, ref:`2.17.2`, q:`Where may OTs park?`, a:`Non-reserved parking spaces on Sycamore St., directly north of the paperclip track and grass sports fields, unless otherwise directed. Do not park next to the Ritchey Center.` },
{ part:8, ref:`2.18`, q:`State the policy on receiving and entertaining guests.`, a:`OTs will not entertain guests at the OTS Complex, including meeting members on or off Maxwell AFB. Exceptions require TRS SQ/CC approval, routed through the OT Chain of Command.` },
{ part:8, ref:`2.19`, q:`State the authorized travel area policy.`, a:`Except for emergency medical issues, travel outside of the local area will not be authorized. Off-base areas and locations are approved by TRS SQ/CC, routed through the OT chain of command.` },
{ part:8, ref:`2.19`, q:`What is the wingman rule on and off campus?`, a:`OTs will travel with a Wingman unless otherwise specified in the manual.` },
{ part:8, ref:`2.20`, q:`State the leave policy while attending OTS.`, a:`OTs are not authorized to take leave while in training.` },
{ part:8, ref:`2.21`, q:`State the mobile phone policy.`, a:`Cell phone use is limited to official use only during SMT. Phones will be away and silenced during scheduled events, unless required for emergency notification purposes.` },
{ part:8, ref:`2.22`, q:`What triggers a Commander's Review, and IAW what publication?`, a:`Failure of an OT's ability to learn, comply, and/or adapt to the military environment, IAW DAFMAN 36-2032, Military Recruiting and Accessions.` },
{ part:8, ref:`2.22`, q:`What are the four possible outcomes of a Commander's Review?`, a:`Reinstated, recycled, disenrolled, or disenrolled with prejudice.` },
{ part:8, ref:`2.22.1`, q:`What is the consequence of failing to meet Department of the Air Force standards, and what may the OT do afterward?`, a:`Disenrollment. OTs may provide a statement after disenrollment proceedings IAW DAFI 36-2907, Adverse Administrative Actions.` },
{ part:8, ref:`2.22.2`, q:`How long does an OT have to submit a CR rebuttal package, and who assists?`, a:`Three days, with assistance from the Area Defense Counsel (ADC).` },

// ─────────── PART 9 — DRESS & APPEARANCE ───────────
{ part:9, ref:`3.1`, q:`IAW what publications do OTs maintain dress and personal appearance standards?`, a:`DAFI 36-2903, Dress and Personal Appearance of United States Air Force and United States Space Force Personnel, and SPFI 36-2903, Dress and Personal Appearance of Military Personnel — to include any AFAC, Maxwell AFB, and OTS Supplements.` },
{ part:9, ref:`3.1`, q:`What does AFAC stand for in the dress and appearance context?`, a:`Air Force Accessions Center.` },
{ part:9, ref:`3.2.1`, q:`List the uniforms and items OTs are not authorized to wear without a waiver.`, a:`The Flight Duty Uniform (FDU), Desert FDU, 2-Piece FDU, and the OCP baseball cap.` },
{ part:9, ref:`3.2.1`, q:`What is the facial hair policy?`, a:`OTs are not authorized facial hair, including mustaches, unless approved with waiver.` },
{ part:9, ref:`3.2.2`, q:`When must the PTG shirt be tucked in?`, a:`Into shorts or running pants while marching, in formation, or while performing group physical training — to include formation runs and double-time.` },
{ part:9, ref:`3.2.2`, q:`When may the PTG shirt be untucked?`, a:`Only during active individual physical training, IAW DAFI 36-2903.` },
{ part:9, ref:`3.3`, q:`What dictates the Uniform of the Day, and who must comply?`, a:`The training schedule dictates the UOD, and it is mandatory for all Officer Trainees.` },
{ part:9, ref:`3.3`, q:`Who is the approval authority for all UOD changes and variations?`, a:`The TRS SQ/DO.` },
{ part:9, ref:`3.3`, q:`After SMT, what other uniforms may be worn, and under what conditions?`, a:`With TRS SQ/DO coordination and approval, other authorized uniforms may be worn, and shall be worn IAW DAFI 36-2903.` },
{ part:9, ref:`3.3`, q:`What do OTs wear to sleep?`, a:`The PTG, unless deviations are approved.` },
{ part:9, ref:`3.4`, q:`What is the standard for hydration systems regarding patches and wear?`, a:`They will be free of patches and will always be worn.` },
{ part:9, ref:`3.4`, q:`Where is the hydration system optional?`, a:`While in the dormitories or latrine.` },
{ part:9, ref:`3.4`, q:`What is the condition standard when the hydration system is worn?`, a:`Everything will be buckled, zipped, or snapped.` },
{ part:9, ref:`3.4`, q:`Where do hydration systems go in the flight room and auditorium?`, a:`On the back of the Officer Trainee's chair, standardized.` },
{ part:9, ref:`3.4`, q:`How are hydration systems handled in service dress or dress blues?`, a:`Hand-carried while wearing service dress or dress blues (Class A / Class B).` },
{ part:9, ref:`3.4`, q:`What change did the 1 December 2025 SPINS make to hydration systems?`, a:`The hydration pack is optional in the latrine.` },
{ part:9, ref:`3.5.1`, q:`How is the reflective belt worn with the utility uniform during darkness versus daylight?`, a:`Around the waist during hours of darkness; secured around the hydration system during hours of light.` },
{ part:9, ref:`3.5.1`, q:`When may the reflective belt be removed or stowed, and who determines that?`, a:`During the execution of scheduled and independent field events, as determined by the TRS SQ/DO.` },
{ part:9, ref:`3.5.1`, q:`What is the reflective belt exception related to the latrine?`, a:`It will be on your person if you are not taking the hydration pack to the latrine.` },
{ part:9, ref:`3.5.2`, q:`How is the reflective belt worn with Class A/Class B blues?`, a:`Secured around the hydration system.` },
{ part:9, ref:`3.5.3`, q:`What are OTs prohibited from doing with the reflective belt?`, a:`Hanging items from it or attaching items to it. OTs keep module-specific reflective belts in good working order.` },
{ part:9, ref:`3.6`, q:`When are eyeglass straps required?`, a:`For all field leadership events and PT.` },
{ part:9, ref:`3.6`, q:`Are contact lenses authorized during field events?`, a:`No.` },
{ part:9, ref:`3.7`, q:`IAW what is the wear of cosmetics governed, and what is specifically not authorized?`, a:`IAW DAFI 36-2903; eyelash extensions are not authorized due to the nature of the training environment.` },
{ part:9, ref:`3.7`, q:`When will cosmetics not be worn?`, a:`During field conditions.` },
{ part:9, ref:`3.8`, q:`State the rule on items not mentioned in the SPINS.`, a:`Items not mentioned within this document does not mean they are authorized. The philosophy of "It doesn't say I can't; therefore, I can" does not apply. If it does not say it is authorized, then it is not authorized.` },
{ part:9, ref:`3.8`, q:`Quote the philosophy that does not apply at OTS.`, a:`"It doesn't say I can't; therefore, I can."` },
{ part:9, ref:`3.5`, q:`State the reflective belt requirement for both uniform categories back to back.`, a:`Utility uniform: waist during darkness, around the hydration system during daylight. Blues Class A/B: secured around the hydration system.` },
{ part:9, ref:`3.2.2`, q:`Is the PTG shirt tucked during a formation run?`, a:`Yes — tucked into shorts or running pants.` },
{ part:9, ref:`2.5.2.1.5`, q:`Is the reflective belt a mandatory carry item?`, a:`Yes — with approved deviations found in Chapter 3.` },
{ part:9, ref:`A3.6.1.5`, q:`In OCPs or PTG at the DFAC, may an OT remove their hydration system?`, a:`No — coats/jackets may go on the back of the chair, but the hydration system is not removed.` },
{ part:9, ref:`A3.6.1.5`, q:`In blues or service uniform at the DFAC, where does the hydration source go?`, a:`On the back of the chair.` },

// ─────────── PART 10 — HEALTH & MEDICAL ───────────
{ part:10, ref:`4.1`, q:`What do IDMTs in the OTS Medical Aid Station provide?`, a:`Basic medical care for OTs, Officer Trainee medical profiles, and coordination of referrals to the base Medical Treatment Facility as needed.` },
{ part:10, ref:`4.1`, q:`May an OT seek treatment at the base MTF on their own?`, a:`No — not without first coordinating with the IDMTs or Flight Commander.` },
{ part:10, ref:`4.1`, q:`What is the rule for OTs with a medical specialty?`, a:`They will not self-prescribe medication or provide medical treatment to other OTs unless life, limb, or permanent sensory impairment is at risk.` },
{ part:10, ref:`4.2`, q:`When are sick call hours briefed?`, a:`During medical in-processing.` },
{ part:10, ref:`4.2`, q:`What must an OT do about events missed during SMT for sick call?`, a:`Notify their instructor of any missed event.` },
{ part:10, ref:`4.2`, q:`Which sick call should OTs make every attempt to report to?`, a:`Morning sick call.` },
{ part:10, ref:`4.2`, q:`What is the Nurse Advice Line number, and what is it required for?`, a:`1-800-874-2273 — medical authorization is required before an OT receives urgent or routine medical care from an off-base provider.` },
{ part:10, ref:`4.2`, q:`What happens if an OT fails to get authorization before off-base urgent or routine care?`, a:`They may incur medical expenses.` },
{ part:10, ref:`4.2`, q:`When is a wingman not required for medical purposes?`, a:`For non-emergency IDMT sick call, or if referred by IDMTs to the Maxwell on-base clinic.` },
{ part:10, ref:`4.3`, q:`What is the emergency procedure for a threat to life, limb, or eyesight?`, a:`Call 911 and state you are located on Maxwell AFB and need to be connected to Maxwell AFB emergency dispatch. Notify the instructor immediately.` },
{ part:10, ref:`4.3`, q:`After off-base emergency treatment, what must an OT do?`, a:`Report to the IDMT the next duty day during morning sick call hours with the off-base medical documentation, and immediately notify their instructor upon returning to campus.` },
{ part:10, ref:`4.4`, q:`Who must be notified of all scheduled medical appointments?`, a:`The instructor and the IDMTs, including potential impacts to SMT.` },
{ part:10, ref:`4.4`, q:`Who approves and coordinates all MTF appointments?`, a:`The IDMTs — they also track all off-base medical care, to include off-base surgeries.` },
{ part:10, ref:`4.4`, q:`After an off-campus medical appointment, what is required?`, a:`Report to the IDMT the next duty day during sick call hours with the medical documentation from the appointment.` },
{ part:10, ref:`4.5`, q:`If placed on quarters by the MTF, who must be notified before going to the dorm room?`, a:`The IDMTs and their Flight Commander.` },
{ part:10, ref:`4.5`, q:`If placed on quarters by the IDMT, who must be notified?`, a:`Their instructor, prior to proceeding to their dorm room.` },
{ part:10, ref:`4.5`, q:`What is the door rule while on medical quarters, and who handles meals?`, a:`The OT leaves their door closed; flights coordinate food requirements with the instructor to ensure meal coverage.` },
{ part:10, ref:`4.6`, q:`How is transportation to the MTF or an off-base appointment arranged?`, a:`By taxi service or, with ADO approval, Trainee POV. Coordinate with OTS Staff prior to requesting Base Taxi.` },
{ part:10, ref:`4.6`, q:`What is the Base Taxi phone number?`, a:`334-953-5038.` },
{ part:10, ref:`4.7.1`, q:`What are AF Form 469 and AF Form 422?`, a:`AF Form 469, Duty Limiting Condition Report; AF Form 422, Notification of Air Force Member's Qualification Status.` },
{ part:10, ref:`4.7.1`, q:`If treated at the base MTF, what must an OT present and to whom?`, a:`A copy of the AF Form 469 or AF Form 422 to the IDMTs and their instructor as soon as possible.` },
{ part:10, ref:`4.7.1`, q:`What happens with documents from an off-base medical facility?`, a:`Present them to the IDMT to establish an AF Form 422, then present a copy of the AF Form 422 to the instructor as soon as possible.` },
{ part:10, ref:`4.7.1`, q:`Which medical document must an OT always carry?`, a:`The original AF Form 422.` },
{ part:10, ref:`4.7.1`, q:`What does the "release date" on the AF Form 422 mean, and what is the release time?`, a:`The date the OT is returned to full duty with no restrictions; release time is lights-on unless otherwise noted.` },
{ part:10, ref:`4.7.1`, q:`What is the consequence of disregarding instructions on the AF Form 422?`, a:`It is considered disobeying a direct order and may result in the OT being liable for the costs of treating further injuries.` },
{ part:10, ref:`4.7.1`, q:`How does an OT get a medical profile extension?`, a:`Report to the IDMT during sick call.` },
{ part:10, ref:`4.7.2`, q:`How quickly must an injury be reported, and to whom?`, a:`Notify the instructor immediately, but no later than 24 hours after the injury occurred.` },
{ part:10, ref:`4.7.2`, q:`What form is filed for an injury, and within what timeframe?`, a:`AF Form 978, Supervisor's Mishap Report, submitted to the instructor within 48 hours.` },
{ part:10, ref:`4.7.2`, q:`When else is an AF Form 978 required, and when is it not?`, a:`Required anytime an OT is involved in a vehicle accident on or off base, whether there were injuries or not. Not required for OTs who become ill.` },
{ part:10, ref:`4.7.2`, q:`Does the injury report requirement apply to off-duty and off-base injuries?`, a:`Yes — either on or off duty/base.` },

// ─────────── PART 11 — SAFETY, HEAT & WEATHER ───────────
{ part:11, ref:`Fig A5.2`, q:`What is the on-base emergency number?`, a:`334-953-9911.` },
{ part:11, ref:`Fig A5.2`, q:`What is the IDMT phone number and its hours?`, a:`334-318-1058, 0700–1600, Monday through Friday.` },
{ part:11, ref:`Fig A5.2`, q:`What is the Nurse Appointment Line number?`, a:`334-953-3368.` },
{ part:11, ref:`Fig A5.2`, q:`What is the Nurse Advice Line number?`, a:`1-800-874-2273.` },
{ part:11, ref:`A5.1`, q:`Which publications cover PFA limitations and thermal stress work/rest cycles?`, a:`DAFMAN 36-2905 for Physical Fitness Assessment limitations; DAFI 48-151, Thermal Stress Program, for physical training, conditioning, and work/rest cycles.` },
{ part:11, ref:`A5.2`, q:`Where is the flag located?`, a:`The Dining Facility.` },
{ part:11, ref:`A5.3`, q:`State the post-meal activity waiting times.`, a:`15 minutes prior to moderate work, 30 minutes prior to heavy work, and 60 minutes prior to very heavy work.` },
{ part:11, ref:`A5.4.1`, q:`Define Lightning Watch and the marching rule.`, a:`Potential within 10 miles. Officer Trainees will march with guidons.` },
{ part:11, ref:`A5.4.2`, q:`Define Lightning Warning and the required action.`, a:`Observed within 5 miles. Officer Trainees will seek shelter and remain indoors.` },
{ part:11, ref:`A2.6`, q:`During "lightning within five," how do OTs transit?`, a:`Quickly, using the most direct route, as individuals or in single file.` },
{ part:11, ref:`A2.6`, q:`List the lightning approved shelter locations.`, a:`The Dojo, LRC, latrines, and the Sim City warehouse.` },
{ part:11, ref:`A2.6`, q:`When is Shelter-in-Place used?`, a:`Only in the event of airborne hazards, such as a chemical spill — then follow SIP procedures.` },
{ part:11, ref:`A2.6`, q:`What is the expectation for judgement in adverse weather, regardless of official notification?`, a:`OTs and OTS staff are expected to exercise sound judgement and risk management practices, regardless of whether an official base notification has been published.` },
{ part:11, ref:`Table A5.1`, q:`Name the five heat categories with their flag colors.`, a:`Category 1 (78–81.9°F), Category 2 GREEN (82–84.9°F), Category 3 YELLOW (85–87.9°F), Category 4 RED (88–89.9°F), Category 5 BLACK (above 90°F).` },
{ part:11, ref:`Table A5.1`, q:`What WBGT range is BLACK flag?`, a:`Greater than 90°F.` },
{ part:11, ref:`Table A5.1`, q:`What WBGT range is RED flag?`, a:`88–89.9°F.` },
{ part:11, ref:`Table A5.1`, q:`What WBGT range is YELLOW flag, and what is GREEN?`, a:`Yellow is 85–87.9°F; green is 82–84.9°F.` },
{ part:11, ref:`Table A5.1`, q:`What is the maximum hourly and daily fluid intake?`, a:`Hourly fluid intake should not exceed 1.25 quarts; daily fluid intake should not exceed 12 quarts.` },
{ part:11, ref:`Table A5.1`, q:`What does NL mean in the work/rest table?`, a:`No limit to work times per hour.` },
{ part:11, ref:`Table A5.1`, q:`Give examples of Easy Work (250 W).`, a:`Weapon maintenance, marksmanship training, drill, and ceremony.` },
{ part:11, ref:`Table A5.1`, q:`Give examples of Moderate Work (425 W).`, a:`Patrolling with a 30 lb load, low and high crawl, digging defensive positions, combatives drill, obstacle course.` },
{ part:11, ref:`Table A5.1`, q:`Give examples of Heavy Work (600 W) and Very Heavy Work (800 W).`, a:`Heavy: patrolling with a 45 lb load, four-person litter carry, jogging 4 mph, combatives live-roll. Very heavy: two-person litter carry, move under direct fire, litter course.` },
{ part:11, ref:`Table A5.1`, q:`What adjustment is made to the WBGT index for body armor, and for MOPP 4?`, a:`Add 5°F for body armor in humid climates; add 10°F (easy work) or 20°F (moderate or hard work) for NBC/MOPP 4.` },
{ part:11, ref:`Table A5.1`, q:`What does "rest" mean in the work/rest table?`, a:`Minimal physical activity — sitting or standing — in the shade if possible.` },
{ part:11, ref:`Fig A5.2`, q:`List heat exhaustion symptoms.`, a:`Headache, dizziness, nausea; weakness, rapid pulse, poor judgment; sweating profusely; shivering and goosebumps; normal or slightly elevated temperature.` },
{ part:11, ref:`Fig A5.2`, q:`List heat stroke symptoms.`, a:`Headache, dizziness, nausea; excessive sweating or red, hot, dry skin; high body temperature (hot to touch); altered mental status/confusion; abnormal behavior/unconsciousness; loss of bowel or bladder control; twitching or convulsions; deep coma with pinpoint pupils.` },
{ part:11, ref:`Fig A5.2`, q:`What is the first aid for heat exhaustion?`, a:`Move the OT to a shady/air-conditioned area, remove outer layers of clothing, pour cold water on head/neck/torso, hydrate with sips of cold water, fan vigorously, and seek medical evaluation if symptoms worsen or do not improve within 60 minutes.` },
{ part:11, ref:`Fig A5.2`, q:`What is the first aid for heat stroke, and what two steps make it different from heat exhaustion?`, a:`Same steps as heat exhaustion, plus use ice sheets and cold packs under the armpits — and call 334-953-9911 immediately.` },
{ part:11, ref:`Fig A5.2`, q:`What are heat cramp symptoms and first aid?`, a:`Muscle spasms and pain, usually in the abdomen, arms, or legs. Rest in a shady, cool area, drink water or other cool beverages, wait a few hours before returning to strenuous work, and seek medical attention if cramps do not go away.` },
{ part:11, ref:`Fig A5.2`, q:`What are heat rash symptoms and treatment?`, a:`Clusters of red bumps on the skin, often on the neck, upper chest, and folds of skin. Work in a cooler, less humid environment when possible and keep the affected area dry.` },
{ part:11, ref:`Fig A5.3`, q:`State the frostbite times for High, Severe, and Extreme Risk.`, a:`High Risk 30 minutes, Severe Risk 10 minutes, Extreme Risk 5 minutes.` },
{ part:11, ref:`Fig A5.3`, q:`State the recommended work/rest warming cycles for each frostbite risk level.`, a:`Low Risk: 50 minutes work / 10 minutes warming. High Risk: 40/20. Severe Risk: 30/30. Extreme Risk: mission critical work only, keep task duration as short as possible.` },
{ part:11, ref:`Fig A5.3`, q:`At what temperature are Vapor Barrier boots worn at Low and High Risk, and what preventive measure appears at every risk level?`, a:`VB boots below 0°F; "avoid sweating" appears at every level.` },
{ part:11, ref:`Fig A5.3`, q:`What is the buddy check interval at High, Severe, and Extreme Risk?`, a:`High Risk: every 20–30 minutes. Severe and Extreme Risk: every 10 minutes, with work groups of no less than two personnel.` },

// ─────────── PART 12 — DRILL DEFINITIONS & FORMATIONS ───────────
{ part:12, ref:`A2.1.1`, q:`Define a Small Marching Unit (SMU).`, a:`A formation of two to four Officer Trainees. Exception: a guidon bearer may march on their own.` },
{ part:12, ref:`A2.1.1`, q:`How is an SMU of three or four properly sized?`, a:`Tallest Officer Trainees in the front and on the right.` },
{ part:12, ref:`A2.1.1`, q:`How is an SMU of two sized?`, a:`The tallest will be to the right.` },
{ part:12, ref:`A2.1.1`, q:`In an SMU with a guidon, who carries it?`, a:`The person on the right.` },
{ part:12, ref:`A2.1.1`, q:`What preparatory command do SMUs use?`, a:`"Detail, …"` },
{ part:12, ref:`A2.1.1`, q:`When calling commands in an SMU, does the OT respond to their own commands?`, a:`Yes — the OT calling commands will respond to their own commands when in an SMU.` },
{ part:12, ref:`A2.1.1`, q:`What preparatory command is used by OTs performing a specific task, such as trash detail or flag detail?`, a:`"Detail, …"` },
{ part:12, ref:`A2.1.1`, q:`With 5 to 7 Officer Trainees, what do you form?`, a:`Multiple SMUs — never make a single SMU greater than 4 Officer Trainees.` },
{ part:12, ref:`A2.1.2`, q:`Define a Flight.`, a:`A formation of eight or more Officer Trainees, including a designated Flight Leader and a guidon bearer.` },
{ part:12, ref:`A2.1.2`, q:`How many elements are in a flight, and at what interval?`, a:`At least two but no more than four elements, at normal interval.` },
{ part:12, ref:`A2.1.2`, q:`On the OTS Complex, how do flights normally march?`, a:`With two elements.` },
{ part:12, ref:`A2.1.2`, q:`Where do OTs on marching waivers walk, and what are they responsible for?`, a:`Six paces behind the flight, extending all military courtesies themselves.` },
{ part:12, ref:`A2.1.3`, q:`What are the Flight Leader's responsibilities?`, a:`Lead the flight and ensure safety, ensure all flight members are accounted for, and assume all responsibility for the flight — including precise flight control through proper command execution and rendering courtesies when appropriate.` },
{ part:12, ref:`A2.1.3`, q:`If a command is improperly given, what do the individuals do?`, a:`Execute the movement to the best of their ability. Flight members will only respond to valid commands.` },
{ part:12, ref:`A2.1.3`, q:`After the command of execution has been given and the movement has begun, what does the Flight Leader do?`, a:`Give other appropriate commands to bring the element to the desired position.` },
{ part:12, ref:`A2.1.4`, q:`Define a Road Guard.`, a:`An Officer Trainee designated to stop traffic while Officer Trainees cross a road or parking lot.` },
{ part:12, ref:`A2.1.5`, q:`Define an Element Leader.`, a:`The leader of the smallest drill unit, comprised of at least three but usually eight to 12 individuals, one of whom is designated the element leader.` },
{ part:12, ref:`A2.1.6`, q:`Define a Drill Command and its two parts.`, a:`An oral order to direct a formation. Most consist of the Preparatory Command, which explains what the movement will be, and the Command of Execution, given after, which explains when the movement will be carried out.` },
{ part:12, ref:`A2.1.6`, q:`Give two examples of commands where the preparatory command and command of execution are combined.`, a:`"FALL IN" and "AT EASE."` },
{ part:12, ref:`A2.1.6`, q:`What are informational commands, and give two examples.`, a:`Commands with no Preparatory Command or Command of Execution that are not supplementary — e.g., "PREPARE FOR INSPECTION" and "COLUMN OF FILES."` },
{ part:12, ref:`A2.1.7`, q:`Define cadence and give it as counted.`, a:`Cadence is the measure or beat of movement, given in sets of two: "HUT, TOOP, THREEP, FOURP; HUT, TOOP, THREEP, FOURP."` },
{ part:12, ref:`A2.1.7`, q:`When do you not initiate cadence?`, a:`If a complete set of two cannot be achieved.` },
{ part:12, ref:`A2.1.8`, q:`Give the sizing verbiage word for word.`, a:`"With the exception of the guidon bearer and element leaders (or with no exception), if you are taller than the Officer Trainee/OT in front of you, tap them on the shoulder and move forward."` },
{ part:12, ref:`A2.1.8`, q:`What must happen to OT flights and squadrons before moving?`, a:`They must be sized.` },
{ part:12, ref:`A2.2.1`, q:`What is the formation leader's first responsibility?`, a:`The safety of the formation.` },
{ part:12, ref:`A2.2.1`, q:`Where should the formation leader position themselves when giving commands?`, a:`At the position of attention and in the best position to observe the flight performing the movement — generally the action side or the direction the flight is moving toward.` },
{ part:12, ref:`A2.2.2`, q:`Where do OTs march at the position of attention?`, a:`On sidewalks, parking lots, troop walks, across active roadways, and other improved surfaces.` },
{ part:12, ref:`A2.2.3`, q:`How long after the last meal may OTs double time, and where?`, a:`After 1 hour has elapsed; on paved surfaces to and from physical conditioning activities, except when crossing the street.` },
{ part:12, ref:`A2.2.3`, q:`What is the double time rule during hours of darkness, and the exception?`, a:`OTs will not double time during hours of darkness for safety reasons. Exception: approved formation runs may take place during dawn and dusk, and if the formation is carrying flashlights or reflective gear.` },
{ part:12, ref:`A2.2.4 / A2.2.5`, q:`What must happen before "Flight, HALT" when marching at ease, and what must formations carry during darkness?`, a:`Flights must be placed back at attention while marching prior to "Flight, HALT." All members must carry operable flashlights during hours of darkness and periods of reduced visibility — reflective gear is a suitable substitute during formation runs.` },

// ─────────── PART 13 — ENTRY/DEPARTURE, MARCHING, GUIDONS ───────────
{ part:13, ref:`A2.2.6`, q:`Why do building entrance procedures exist, and who do they apply to?`, a:`To promote good order and discipline among OTs while entering any permanent structure; they apply to squadron, flight, and SMU formations.` },
{ part:13, ref:`A2.2.6`, q:`If a door becomes propped in the open position, who closes it?`, a:`The last Officer Trainee entering.` },
{ part:13, ref:`A2.2.6.1`, q:`Give the Column of Files command.`, a:`"COLUMN OF FILES from the right (left), forward, MARCH."` },
{ part:13, ref:`A2.2.6.1`, q:`On the preparatory command, what does the element leader of the moving element do?`, a:`Turns their head 45 degrees to the right (left) and commands "Forward."` },
{ part:13, ref:`A2.2.6.1`, q:`What do the remaining element leaders command on the preparatory command?`, a:`They turn their heads 45 degrees to the right (left) and command "STAND FAST," keeping their heads turned until they step off.` },
{ part:13, ref:`A2.2.6.1`, q:`On "March" in a column of files, who steps off first and what happens next?`, a:`The extreme right (left) element steps off. Each remaining element leader commands "Forward, MARCH" as the last OT in each element passes, ensuring their element is in step with the preceding element.` },
{ part:13, ref:`A2.2.6.1`, q:`In a column of files from the left, what does the guide do on the informational command?`, a:`Execute a face in marching, then right face in front of the file that will move first, and remain at carry guidon.` },
{ part:13, ref:`A2.2.6.2`, q:`Who holds the door for the flight, and who holds it for the initial element leader?`, a:`The initial element leader holds the door for the flight; the Flight Leader holds the door for the initial element leader.` },
{ part:13, ref:`A2.2.6.2`, q:`Who is the last person from the flight to enter a building?`, a:`The Flight Leader.` },
{ part:13, ref:`A2.2.6.2`, q:`What does the guidon bearer do when entering a building?`, a:`Place the guidon in the guidon stand, if available.` },
{ part:13, ref:`A2.2.6.3`, q:`Give the SMU commands when entering a building or leaving the general area.`, a:`"Flight, HALT, COVER," followed by "DISMISSED."` },
{ part:13, ref:`A2.2.6.3`, q:`When is "FALL OUT" given instead of "DISMISSED"?`, a:`If remaining in the general area — such as after meals when leaving the DFAC to join the larger flight formation.` },
{ part:13, ref:`A2.2.7`, q:`Who is the first member of the flight to depart a building, and what do they do?`, a:`The Flight Leader — they designate the position for forming the flight.` },
{ part:13, ref:`A2.2.7`, q:`Who ensures building doors close on departure, and what command may be used after open ranks instruction?`, a:`The last Officer Trainee in the formation; flights may use the command "FALL IN."` },
{ part:13, ref:`A2.2.7`, q:`What must Flight Leaders take care not to do when forming up outside a building?`, a:`Block traffic into or out of the building.` },
{ part:13, ref:`A2.2.7.1`, q:`How does an SMU depart an academic building?`, a:`Exit in an orderly manner and form up on the sidewalk — there will be no talking in formation.` },
{ part:13, ref:`A2.2.7.2`, q:`Give the statement to join a formed flight.`, a:`Salute and state, "Sir/ma'am, (officer trainee) (name), requests permission to join the flight."` },
{ part:13, ref:`A2.2.7.2`, q:`How does the Flight Leader respond to a request to join the flight?`, a:`Return the salute and instruct the OT to "FALL IN," or "Size yourself in" if the formation has been previously sized.` },
{ part:13, ref:`A2.2.7.3`, q:`How does an acting Flight Leader hand control back to the designated Flight Leader?`, a:`They exchange salutes and the Flight Leader instructs the acting Flight Leader to "FALL IN" or "Size yourself in" if previously sized.` },
{ part:13, ref:`A2.2.7.3`, q:`What must the regaining Flight Leader do before giving a command?`, a:`Ensure the flight is aware that they are now in command of the formation.` },
{ part:13, ref:`A2.3.1`, q:`Who escorts flights to activities requiring outdoor transit, and what changes that?`, a:`OTS staff escort flights; upon passing the pennant test, flights can march without OTS staff direct supervision.` },
{ part:13, ref:`A2.3.1`, q:`What is the exception to marching without staff supervision after the pennant test?`, a:`Initial off-campus transit must be monitored by staff.` },
{ part:13, ref:`A2.3.1`, q:`Name the three cases where flight integrity may be broken.`, a:`1) OT senior leadership and designated key staff may march alone to monitor formation activity. 2) OTs may march in pairs to work details. 3) To meet individual appointments or perform individual PT.` },
{ part:13, ref:`A2.3.1.3`, q:`What is the safety rule for aerobics/exercise programs?`, a:`Two or more Officer Trainees must participate together.` },
{ part:13, ref:`A2.3.2`, q:`Must OTs march while escorting guests during authorized times?`, a:`No — but they will maintain a professional military image and render proper military courtesies.` },
{ part:13, ref:`A2.3.4`, q:`State the right of way rules for formations.`, a:`Under normal conditions a formation will not pass another formation on the march. Formations/SMUs may pass stationary formations without requesting permission. A stationary formation leader must yield to a formation underway. If converging while on the march, leaders yield to formations on their right.` },
{ part:13, ref:`A2.3.5`, q:`What surfaces do OTs plan to march on?`, a:`Improved surfaces only — do not walk or march across grass surfaces unless directed by OTS staff or for safety reasons.` },
{ part:13, ref:`A2.5.1`, q:`When do flights carry their flight guidon?`, a:`From the start to the end of the academic day while marching from one location to another on Maxwell AFB, except when instructed otherwise by this manual or staff, or due to weather restrictions.` },
{ part:13, ref:`A2.5.1`, q:`What are squadron guidons used for?`, a:`Official functions only.` },
{ part:13, ref:`A2.5.2`, q:`To which events is the guidon NOT carried?`, a:`Blue Thunder, the Leadership Reaction Course, field events held off complex, and PT.` },
{ part:13, ref:`A2.5.2 / A2.5.3`, q:`State the guidon handling prohibitions.`, a:`Guidons will not be posted by jamming them into the ground, will not be placed with the tip of the ornament on the ground, and will not have the pennant wrapped tightly around the staff.` },
{ part:13, ref:`A2.5.3`, q:`Where is the guidon placed during drill class or parade practice, and what is announced when entering a building with a guidon?`, a:`By the first set of bleachers. Announce "Guidon" to alert others in the area to the hazard; if there is no storage rack, place it out of the way, leaning into a corner so it will not fall.` },
{ part:13, ref:`A2.5.4`, q:`What do OTs do if part of the guidon breaks?`, a:`Do not attempt to repair it — take it to the Military Drill and Ceremony (MDC) NCOIC for repair.` },
{ part:13, ref:`A2.5.4`, q:`What are the rules for marking guidons?`, a:`Do not mark guidons on the staff; marking guidons without pennants will be on the ferrule so as not to damage the staff. Once the guidon has a pennant, all additional markings will be removed.` },

// ─────────── PART 14 — ROAD GUARDS ───────────
{ part:14, ref:`A2.4.1.1`, q:`What is the purpose of road guards?`, a:`To ensure the safety of Officer Trainees during transit around the OTS campus and Maxwell AFB.` },
{ part:14, ref:`A2.4.1.1`, q:`For what size formations are road guards required?`, a:`All student formations greater than eight students.` },
{ part:14, ref:`A2.4.1.1`, q:`For flights of seven or smaller, who functions as road guard?`, a:`The Flight Leader.` },
{ part:14, ref:`A2.4.1.1`, q:`Do SMUs require road guards?`, a:`No — formations of two to four students do not require road guards.` },
{ part:14, ref:`A2.4.1.2`, q:`Who serves as road guard within an element?`, a:`The last individual(s) in the rear of each element.` },
{ part:14, ref:`A2.4.1.2`, q:`List the required road guard safety equipment.`, a:`Fluorescent/reflective vest if transiting off campus, reflective belt, and flashlight during hours of darkness.` },
{ part:14, ref:`A2.4.1.2`, q:`How many road guards does a squadron formation require, and how are they positioned?`, a:`Four — positioned in groups of two, approximately six paces ahead of and behind the formation.` },
{ part:14, ref:`A2.4.1.2`, q:`When might more or fewer than two road guards be warranted?`, a:`Occasionally, such as at intersections with greater than two possible vehicular traffic routes.` },
{ part:14, ref:`A2.4.1.3`, q:`What does "piggybacking" units mean, and is it authorized?`, a:`Marching more than one unit across the street without allowing traffic to proceed between them. OTs will not piggyback units; OTS staff may do so only when deemed necessary but will make every effort not to obstruct traffic.` },
{ part:14, ref:`A2.4.1.4`, q:`Who renders courtesies for the flight, and when does the person in charge render them for a passing vehicle?`, a:`The Flight Leader renders all courtesies. If an officer on foot or a staff vehicle passes from the front, the person in charge renders courtesies.` },
{ part:14, ref:`A2.4.1.4`, q:`A staff vehicle approaches while the flight is crossing an intersection. Walk through the response.`, a:`The road guard will not salute due to safety. The person in charge marches the flight across the street, halts the flight, calls in the road guards, and then renders courtesies to the staff vehicle.` },
{ part:14, ref:`A2.4.2.1`, q:`Why are flights halted prior to entering a hazard area?`, a:`For safety — so the Flight Leader can ensure the safety of the posting road guards.` },
{ part:14, ref:`A2.4.2.1`, q:`What counts as a hazard area?`, a:`All intersections where vehicular transit occurs, including parking lots.` },
{ part:14, ref:`A2.4.2.2`, q:`Where does the Flight Leader post after halting the flight?`, a:`Move forward and post in front of the flight at the sidewalk or hazard edge.` },
{ part:14, ref:`A2.4.2.3`, q:`How does the Flight Leader signal traffic to stop?`, a:`By extending either arm and displaying the palm of the hand with the fingers pointed upward — or wave traffic past.` },
{ part:14, ref:`A2.4.2.4`, q:`What does the Flight Leader do after motioning traffic to stop?`, a:`March into the intersection, post in the middle of the road, perform an about face so they are facing the flight, ensure traffic is stopped, and command "Road guards, OUT."` },
{ part:14, ref:`A2.4.2.5`, q:`On "Road guards, OUT," what do the road guards do?`, a:`Go to the lane as directed by the Flight Leader and face oncoming traffic at modified parade rest, with the right arm up and palm flat, fingers pointed upward.` },
{ part:14, ref:`A2.4.2.5`, q:`How is a flashlight held by a posted road guard?`, a:`In the extended arm, with the beam pointed down.` },
{ part:14, ref:`A2.4.2.6`, q:`What does the Flight Leader do while the flight crosses?`, a:`Command the flight to march across the intersection and perform the necessary facing movements so they can always observe the flight.` },
{ part:14, ref:`A2.4.2.7`, q:`What happens once the flight is through the intersection?`, a:`The Flight Leader halts the flight and commands "Road guards, IN."` },
{ part:14, ref:`A2.4.2.8`, q:`Where does the Flight Leader stay while road guards return?`, a:`In the intersection, continuing to halt existing traffic while the road guards return to the rear of the flight.` },
{ part:14, ref:`A2.4.2.9`, q:`When may the Flight Leader give further commands such as "Forward, MARCH"?`, a:`Not until rejoining the flight.` },
{ part:14, ref:`A2.4.2.10`, q:`What is reported about a vehicle that fails to observe safety precautions, and to whom?`, a:`The time, place, type of vehicle, license number if known, and description of the violation — reported to their instructor.` },
{ part:14, ref:`A2.4.2.11`, q:`Two formations approach opposite ends of a hazard. Who has priority?`, a:`The formation proceeding to an appointment has priority; the returning formation must yield, move to the side opposite the hazard and out of the path, then resume transit and execute all road guard procedures as needed.` },
{ part:14, ref:`A2.4.2`, q:`Recite the road guard sequence from halt to step off.`, a:`Halt the flight before the hazard; Flight Leader posts at the hazard edge; wave traffic past or motion it to stop; march to the middle of the road, about face, confirm traffic stopped, command "Road guards, OUT"; road guards post at modified parade rest facing traffic; march the flight across; halt the flight; command "Road guards, IN"; hold traffic until they return; rejoin the flight before giving further commands.` },
{ part:14, ref:`Att 7`, q:`In the field leadership pre-brief formation, what are the five roles in the legend?`, a:`TL = Team Leader, P = Participant, TK = Timekeeper, S = Safety, SL = Safety Leader.` },
{ part:14, ref:`Att 7`, q:`Describe the field leadership pre-brief formation.`, a:`A front rank of Safety personnel with the Safety Leader on the left end and the Timekeeper on the right end, a second rank of Participants behind them, the Team Leader posted forward of the formation, and Staff facing the Team Leader.` },
{ part:14, ref:`Att 7`, q:`Describe the field leadership de-brief formation.`, a:`A U-shaped (horseshoe) formation with Safety personnel and the Safety Leader on one side, Participants on the other, the Team Leader at the near end of the Participant side, and Staff outside the opening.` },
{ part:14, ref:`2.7.6.3`, q:`For which type of events do OTs form up IAW Attachment 7?`, a:`Field leadership events, such as the Leadership Reaction Course — for pre- and post-event briefs.` },
{ part:14, ref:`A2.4.1.2`, q:`When is a fluorescent/reflective vest required for road guards?`, a:`If transiting off campus.` },

// ─────────── PART 15 — DFAC ARRIVAL ───────────
{ part:15, ref:`A3.1`, q:`How many meals are OTs typically scheduled to eat at the DFAC, and what if they choose not to eat?`, a:`Three meals daily; OTs who choose not to eat are still required to process through the DFAC.` },
{ part:15, ref:`A3.1`, q:`When should the menu be reviewed and why?`, a:`Prior to entering the serving line, to expedite processing.` },
{ part:15, ref:`A3.1`, q:`What are the rules on food waste and taking food from the DFAC?`, a:`OTs will make a reasonable attempt to consume all food purchased to minimize waste; food will not be taken from the DFAC without prior coordination and staff approval.` },
{ part:15, ref:`A3.1`, q:`What kind of conversation is not authorized in the DFAC?`, a:`Extraneous conversation.` },
{ part:15, ref:`A3.2`, q:`Define Dining Priorities (DP).`, a:`Scheduled times when flights are required to arrive at the DFAC bays.` },
{ part:15, ref:`A3.2`, q:`How many DPs is each flight typically assigned?`, a:`Three — breakfast, lunch, and dinner — unless the weekly training schedule directs otherwise.` },
{ part:15, ref:`A3.2`, q:`Do DPs apply on weekends and holidays?`, a:`Yes — OTs will meet all flight DPs, even those on a weekend or holiday.` },
{ part:15, ref:`A3.2`, q:`Who is exempt from meeting their flight's DP?`, a:`OTs performing assigned details during their scheduled DPs.` },
{ part:15, ref:`A3.3`, q:`When do Mess Checkers and Chow Sharks arrive, and how long do they work?`, a:`Five minutes prior to the student squadron's first scheduled DP; they work as a team until the last flight has met their DP.` },
{ part:15, ref:`A3.3`, q:`What do Mess Checkers do after the last scheduled meal of the day?`, a:`Place their DP rosters in their respective CQ binders.` },
{ part:15, ref:`A3.3`, q:`May Mess Checkers or Chow Sharks leave a session early for these duties?`, a:`No — they will not leave an academic or training session early to perform these assigned duties.` },
{ part:15, ref:`A3.3.1`, q:`What authority does the Mess Checker have?`, a:`To clear flights into the DFAC early or late, if entry will not inhibit any other flight's on-time entry.` },
{ part:15, ref:`A3.3.2`, q:`What is the Chow Shark responsible for?`, a:`Ensuring all Officer Trainees follow proper procedures inside the DFAC.` },
{ part:15, ref:`A3.4`, q:`What do flights execute upon arrival at the hold line during DP hours?`, a:`Mark Time — for extended delays or at the Flight Leader's discretion, halt the flight.` },
{ part:15, ref:`A3.4`, q:`What is the arrival window for DP?`, a:`No more than plus or minus three minutes of their scheduled DP time.` },
{ part:15, ref:`A3.4`, q:`What counts as the official arrival time?`, a:`The time arrived at their initial hold line.` },
{ part:15, ref:`A3.4.1`, q:`May OTs bring academic material or backpacks to the DFAC?`, a:`No — unless directed by OTS staff or during hazardous weather conditions.` },
{ part:15, ref:`A3.4.2`, q:`After the hold line, where do Flight Leaders march the flight?`, a:`Into either unoccupied exterior/overhang bay.` },
{ part:15, ref:`A3.4.3`, q:`Give the Flight Leader's report-in statement to the Mess Checker.`, a:`"Sir/Ma'am, flight reports with a dining priority of ___. We arrived at ___."` },
{ part:15, ref:`A3.4.3`, q:`Walk through the Flight Leader's actions once the flight is in an exterior bay.`, a:`The flight remains at attention; the Flight Leader takes the most direct and unobstructed route to within two paces in front of the Mess Checker, initiates a salute, and gives the report-in statement.` },
{ part:15, ref:`A3.4.3`, q:`What does the Mess Checker do if the flight arrives outside their window?`, a:`Determine if the flight may proceed into the DFAC, wait until their scheduled time, or wait until after the last flight enters.` },
{ part:15, ref:`A3.4.3`, q:`After reporting in, what does the Flight Leader do?`, a:`Give the greeting of the day, return to their flight, and wait to enter the DFAC.` },
{ part:15, ref:`A3.4.3`, q:`When may flights be "AT EASE" outside the DFAC?`, a:`Until the inside bay is clear and they are prepared to enter — but only after they have reported in.` },
{ part:15, ref:`A3.4.3`, q:`Who does the Mess Checker report early and late arrivals to?`, a:`The OT Wing Commander — along with their resolution.` },
{ part:15, ref:`A3.4.3`, q:`Who drops their salute first between the Mess Checker and Flight Leader, and why?`, a:`The Mess Checker always drops their salute first, due to the positional authority of the Mess Checker.` },
{ part:15, ref:`A3.4.4`, q:`What command does the Flight Leader use to enter the DFAC, and which file enters first?`, a:`"COLUMN OF FILES" — the file closest to the center of the building enters the DFAC first.` },
{ part:15, ref:`A3.4.4`, q:`What do the guidon bearer and Flight Leader do when entering the DFAC?`, a:`The guidon bearer places the guidon in the guidon stand and falls in at the rear of the flight; the Flight Leader holds open the door and enters last.` },
{ part:15, ref:`A3.4.5`, q:`How many flights may seek shelter under the DFAC overhang, and what is the tertiary hold position?`, a:`Up to six flights; the PCC is the tertiary hold position during lightning storms if the center of the overhang is full.` },
{ part:15, ref:`A3.4.5`, q:`How do OTs approach the DFAC during inclement weather?`, a:`By the most direct means available to the DFAC entry overhang; if interior entry bays are full, flights march under the overhang using as much overhang as possible. Once inside, procedures resume as normal starting with the hold line.` },
{ part:15, ref:`Fig A3.1`, q:`What features are shown in the outside layout of the DFAC?`, a:`A left bay and right bay, three flight positions (Positions #1, #2, and #3), hold lines, and a guidon stand.` },

// ─────────── PART 16 — DFAC INTERIOR & DEPARTURE ───────────
{ part:16, ref:`A3.5`, q:`When may OTs perform facing movements and pivots in the DFAC?`, a:`When not carrying food or utensils, or on carpeted areas.` },
{ part:16, ref:`A3.5`, q:`How are all movements in the serving line accomplished?`, a:`In a modified position of attention.` },
{ part:16, ref:`A3.5.1`, q:`When is talking allowed in the DFAC?`, a:`Only when making on-the-spot corrections, issuing required commands, or when directly addressed by OTS and/or DFAC staff.` },
{ part:16, ref:`A3.5.1`, q:`Give the three authorized phrases for passing others in the DFAC.`, a:`"Sir/Ma'am, excuse me," "Excuse me, Sir/Ma'am," or "Pardon me please, Sir/Ma'am."` },
{ part:16, ref:`A3.5.2`, q:`Upon entering the DFAC, how do OTs form up?`, a:`In two columns beginning abreast the corner edge of the wall, at the position of attention, at close interval from each other and from the wall.` },
{ part:16, ref:`A3.5.3`, q:`Who checks that the area is clear to proceed, and what do they announce?`, a:`The OT closest to the wall looks both ways; once clear they turn their head away from the wall and announce "POST" to their wingman.` },
{ part:16, ref:`A3.5.3`, q:`How many OTs proceed into the serving area at a time, and which serving area may they use?`, a:`The first two OTs in line; they may enter using either the open tray or silverware serving area.` },
{ part:16, ref:`A3.5.4`, q:`While transiting to the serving area, how do the two OTs move?`, a:`Fall in file and in step behind one another, with the OT who called "POST" walking in front.` },
{ part:16, ref:`A3.5.4`, q:`Once aligned with the tray and silverware serving area, what happens?`, a:`The OTs halt, the OT in the back calls "POST," and both do a facing movement toward the tray and silverware serving area.` },
{ part:16, ref:`A3.5.4`, q:`How is the tray oriented when taken?`, a:`With the narrow side of the tray facing away from them as they continue down the serving line.` },
{ part:16, ref:`A3.5.5`, q:`How do OTs move through the serving line, and how is the tray held?`, a:`Sidestep through the entire serving line, keeping the tray on the serving area rails with two hands in contact with the tray at all times.` },
{ part:16, ref:`A3.5.5`, q:`Who pays at the cashier, and what should they have ready?`, a:`Direct Commissioned Officer Trainees must pay for their meal; have the form of payment ready prior to arrival at the cashier to expedite processing.` },
{ part:16, ref:`A3.5.5`, q:`What do Line Officer Trainees do at the cashier?`, a:`Stop and wait for the cashier to account for meal items.` },
{ part:16, ref:`A3.5.6`, q:`What are the two rules on squaring corners and consuming food?`, a:`OTs will not square corners while carrying trays, and will only consume food and drink after seated at their table.` },
{ part:16, ref:`A3.6.1`, q:`How do OTs fill the dining area?`, a:`Proceed to the same side seating area, quickly fill the farthest row of tables from the serving line first, filling in the furthest open table in the row, and use the aisle way preceding the table where they will sit. When filling seats, start with the farthest open chair.` },
{ part:16, ref:`A3.6.1.1`, q:`Where does an OT stand upon arriving at their table, and why?`, a:`At the position of attention behind their chair, to be seen by their wingman; once a wingman joins them, they take their seat.` },
{ part:16, ref:`A3.6.1.1`, q:`Who gives the command to sit at the table, and what is it?`, a:`The last trainee to arrive at the table states "take your seats," and all OTs are seated.` },
{ part:16, ref:`A3.6.1.1`, q:`How many OTs may a table accommodate, and what is the restriction on joining?`, a:`Up to four Officer Trainees; do not join a table which has already sat.` },
{ part:16, ref:`A3.6.1.1`, q:`May an OT sit alone at a table?`, a:`Yes — provided they wait a reasonable time for a wingman, or as advised by the Chow Shark.` },
{ part:16, ref:`A3.6.1.2`, q:`What does a seated OT do when addressed by a staff member?`, a:`Finish chewing, swallow their food, then respond appropriately.` },
{ part:16, ref:`A3.6.1.3`, q:`How long do OTs have to finish their meals, and who can change that?`, a:`Up to 10 minutes after sitting, unless otherwise directed by the TRS SQ/CC.` },
{ part:16, ref:`A3.6.1.4`, q:`Walk through leaving the table for additional food or drink.`, a:`Push in the chair, come to the position of attention, proceed to the serving line using the row in which they entered, and transit using the outermost rows. Upon returning, place food/drink on the tray, come to the position of attention, then sit down.` },
{ part:16, ref:`A3.6.1.5`, q:`Where does other gear go while seated at the DFAC?`, a:`Neatly under the table, resting on top of their feet, leaning against their shins, with all straps and material stowed away. Once seated, bring the chair in as far as possible to avoid congesting the aisle way.` },
{ part:16, ref:`A3.6.2.1`, q:`Once finished eating or the time limit has elapsed, what is the sequence?`, a:`Stand, don gear, standardize, ground chairs to the table, assume the position of attention behind the chair, and prepare to depart.` },
{ part:16, ref:`A3.6.2.2`, q:`How are trays handled and the table cleaned?`, a:`Stack trays in pairs of two and wipe down the table, catching crumbs in the trays. Do not place glassware inside other glassware. Exit toward the windows, maintaining directional flow of traffic, transiting using the outermost rows.` },
{ part:16, ref:`A3.6.2.3`, q:`How are trays placed in the tray cabinet, and why?`, a:`Beginning at the bottom, to prevent a top-heavy cabinet.` },
{ part:16, ref:`A3.6.2.4`, q:`If receiving a "to-go" meal, how does the OT depart?`, a:`Depart the DFAC via the dining area exit, after the cashier transaction.` },
{ part:16, ref:`A3.7.1`, q:`Which doors do OTs use to exit the DFAC, and how do they move to the staging area?`, a:`The doors closest to the parade field, unless directed otherwise; march alone or in single file to their respective staging area.` },
{ part:16, ref:`A3.7.2`, q:`What are the guidon bearer's rules for retrieving the guidon after the DFAC?`, a:`March to the front of the DFAC to retrieve the guidon and return to the flight, abiding hold line procedures. Do not use the front/main entrance, and do not hand carry any items while retrieving the guidon.` },
{ part:16, ref:`A3.7.3`, q:`How do OTs form up after departing the DFAC?`, a:`In column formation in the designated area, quietly waiting for remaining flight members; once all are present, the Flight Leader forms and sizes the flight to march to the next training event.` },
{ part:16, ref:`A3.7.4`, q:`How do OTs depart the DFAC during lightning storms?`, a:`Exit on the side closest to Welch Field and proceed directly to Gilbert Hall, in single file, expeditiously, to gain accountability of the flight — or as otherwise dictated by OTS staff or the OT chain of command.` },
{ part:16, ref:`A3.7.4`, q:`What must OTs NOT do when departing the DFAC during lightning within five?`, a:`Do not collect guidon staffs.` },
];

