import test from 'node:test';
import assert from 'node:assert/strict';
import {zipSync,strToU8} from 'fflate';
import {parseWorkbook,isRed} from '../src/parser.mjs';
import {compile,evaluate,UNKNOWN} from '../src/formula.mjs';
export function fixture({sheet,styles='',strings='',extra={}}={}){return zipSync(Object.fromEntries(Object.entries({
  'xl/workbook.xml':'<workbook xmlns:r="urn:rel"><sheets><sheet name="Schedule" sheetId="1" r:id="r1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels':'<Relationships><Relationship Id="r1" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/styles.xml':styles||'<styleSheet><fonts><font><color rgb="FF000000"/></font><font><color rgb="FFFF0000"/></font></fonts><fills><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFC7CE"/></patternFill></fill></fills><cellXfs><xf fontId="0" fillId="0"/><xf fontId="1" fillId="0"/><xf fontId="0" fillId="1"/></cellXfs><dxfs><dxf><font><color rgb="FF9C0006"/></font><fill><patternFill><bgColor rgb="FFFFC7CE"/></patternFill></fill></dxf><dxf><font><color rgb="FF008000"/></font><fill><patternFill><bgColor rgb="FFC6EFCE"/></patternFill></fill></dxf></dxfs></styleSheet>',
  'xl/sharedStrings.xml':strings||'<sst><si><t>Task A</t></si></sst>',
  'xl/worksheets/sheet1.xml':sheet||'<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" s="1"><v>12</v></c><c r="C1" s="2"><v>9</v></c></row></sheetData></worksheet>',...extra
}).map(([k,v])=>[k,strToU8(v)])));}
test('font and fill red are consolidated by row with references and safe original values',()=>{const s=parseWorkbook(fixture());assert.equal(s.flagged_cells,2);assert.equal(s.flagged_rows,1);assert.deepEqual(s.rows[0].items.map(c=>c.cell),['B1','C1']);assert.equal(s.rows[0].context[0].value,'Task A');assert.equal(s.coverage,'supported_rules');});
test('recognizes dark red and pale red, excludes orange, purple, neutral and green',()=>{for(const c of ['#FF0000','#9C0006','#FFC7CE','#C00000'])assert.ok(isRed(c),c);for(const c of ['#ED7D31','#FFFF00','#FF00FF','#CCCCCC','#008000'])assert.equal(isRed(c),false,c);});
test('conditional comparisons use cached values and enforce priority plus stopIfTrue',()=>{const sheet='<worksheet><sheetData><row r="1"><c r="B1" s="1"><f>10+2</f><v>12</v></c><c r="C1"><v>8</v></c></row></sheetData><conditionalFormatting sqref="B1:C1"><cfRule type="cellIs" operator="greaterThan" dxfId="1" priority="1" stopIfTrue="1"><formula>10</formula></cfRule><cfRule type="cellIs" operator="greaterThan" dxfId="0" priority="2"><formula>5</formula></cfRule></conditionalFormatting></worksheet>';const s=parseWorkbook(fixture({sheet}));assert.deepEqual(s.rows[0].items.map(i=>i.cell),['C1']);assert.equal(s.rows[0].items[0].reasons[0].source,'conditional');});
test('relative and absolute references, AND and OR expressions are interpreted without execution',()=>{const sheet='<worksheet><sheetData><row r="2"><c r="A2"><v>12</v></c><c r="B2"><v>10</v></c></row><row r="3"><c r="A3"><v>3</v></c><c r="B3"><v>10</v></c></row></sheetData><conditionalFormatting sqref="A2:A3"><cfRule type="expression" dxfId="0" priority="1"><formula>AND(A2&gt;$B2,OR(A2&lt;&gt;0,A2=0))</formula></cfRule></conditionalFormatting></worksheet>';const s=parseWorkbook(fixture({sheet}));assert.equal(s.flagged_cells,1);assert.equal(s.rows[0].items[0].cell,'A2');assert.equal(compile('fetch("https://example.test")'),null);assert.equal(evaluate(compile('SUM(A1:A3)'),()=>0,{row:1,col:1},{row:1,col:1}),UNKNOWN);});
test('unsupported formatting is reported, never presented as complete or clear',()=>{const sheet='<worksheet><sheetData><row r="1"><c r="A1"><v>1</v></c></row></sheetData><conditionalFormatting sqref="A1"><cfRule type="expression" dxfId="0" priority="1"><formula>UNSUPPORTED(A1)</formula></cfRule><cfRule type="colorScale" priority="2"/></conditionalFormatting></worksheet>';const s=parseWorkbook(fixture({sheet}));assert.equal(s.flagged_cells,0);assert.equal(s.coverage,'partial');assert.ok(s.warnings.some(w=>w.code==='rule_unsupported'));assert.ok(s.warnings.some(w=>w.code==='visual_rule'));});
test('missing formula results are not silently interpreted as zero',()=>{const sheet='<worksheet><sheetData><row r="1"><c r="A1" s="1"><f>1+2</f></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({sheet}));assert.equal(s.flagged_cells,0);assert.ok(s.warnings.some(w=>w.code==='missing_values'));});
test('indexed colors, theme colors and tints resolve red styles',()=>{const styles='<styleSheet><fonts><font><color indexed="10"/></font><font><color theme="4" tint="0.5"/></font></fonts><cellXfs><xf fontId="0"/><xf fontId="1"/></cellXfs></styleSheet>',sheet='<worksheet><sheetData><row r="1"><c r="A1"><v>1</v></c><c r="B1" s="1"><v>2</v></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({styles,sheet,extra:{'xl/theme/theme1.xml':'<theme><themeElements><clrScheme><accent1><srgbClr val="FF0000"/></accent1></clrScheme></themeElements></theme>'}}));assert.equal(s.flagged_cells,2);});
test('red numeric formats apply only to the relevant number section',()=>{const styles='<styleSheet><numFmts><numFmt numFmtId="164" formatCode="0;[Red]-0;0"/></numFmts><cellXfs><xf numFmtId="164"/></cellXfs></styleSheet>',sheet='<worksheet><sheetData><row r="1"><c r="A1"><v>-5</v></c><c r="B1"><v>5</v></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({styles,sheet}));assert.equal(s.flagged_cells,1);assert.equal(s.rows[0].items[0].cell,'A1');});
test('rich text, escaped HTML and row styles remain plain source data',()=>{const strings='<sst><si><r><t>&lt;script&gt;</t></r><r><t>alert(1)&lt;/script&gt;</t></r></si></sst>',sheet='<worksheet><sheetData><row r="1" s="1" customFormat="1"><c r="A1" t="s"><v>0</v></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({strings,sheet}));assert.equal(s.rows[0].items[0].value,'<script>alert(1)</script>');});
test('rejects document entities, oversized files and invalid files',()=>{assert.throws(()=>parseWorkbook(fixture({sheet:'<!DOCTYPE worksheet [<!ENTITY x "bad">]><worksheet/>'})),/entities/);assert.throws(()=>parseWorkbook(new Uint8Array(17*1024*1024)),/16 MB/);assert.throws(()=>parseWorkbook(new Uint8Array([1,2,3])));});
test('empty cached numeric formula results are reported as unavailable',()=>{const sheet='<worksheet><sheetData><row r="1"><c r="A1" s="1"><f>1+2</f><v/></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({sheet}));assert.equal(s.flagged_cells,0);assert.ok(s.warnings.some(w=>w.code==='missing_values'));});
test('red rich-text runs are identified even when the cell font is neutral',()=>{const strings='<sst><si><r><rPr><color rgb="FFFF0000"/></rPr><t>Needs review</t></r></si></sst>',sheet='<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c></row></sheetData></worksheet>';const s=parseWorkbook(fixture({strings,sheet}));assert.equal(s.flagged_cells,1);assert.equal(s.rows[0].items[0].reasons[0].source,'rich text');});
